<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>lab2 – Lab Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-Lab3.html" rel="next">
<link href="./01-intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-6561bbde787c299e21493071c8edc6ff.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1efbf008e2baeeb4cb205a51dd9b7791.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./brand/uofg-keyline.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lab Workbook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="./assessments/assessments.html"> 
<span class="menu-text">Assessments</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/UGQuants/quants_workbook" title="Workbook GitHub" class="quarto-navigation-tool px-1" aria-label="Workbook GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"></h1>
        </a>     
    </div>
  </nav><div id="quarto-announcement" data-announcement-id="2d92ee72f5f7cb3880c08507c300d9e0" class="alert alert-info hidden">
<i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><strong>Reminder</strong> - check your email for your Posit Cloud group join link, links are also available in the lab group forums on Moodle.</p>
</div>
<i class="bi bi-x-lg quarto-announcement-action"></i>
</div>
</header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 1</strong> Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Lab2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><strong>Lab 2</strong> Data in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Lab3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 3</strong> Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Lab4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 4</strong> Exploratory Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Lab5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 5</strong> Reporting in R Markdown</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Lab6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 6</strong> Visual Exploratory Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Lab7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 7</strong> Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Lab8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 8</strong> Simple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Lab9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 9</strong> Multiple Linear Regression (part 1)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Lab10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 10</strong> Multiple Linear Regression (part 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Lab11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 11</strong> Interpretive Report Assessment</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Answers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workbook suggested answers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#data-in-r" id="toc-data-in-r" class="nav-link active" data-scroll-target="#data-in-r">Data in R</a>
  <ul class="collapse">
<li><a href="#welcome-back" id="toc-welcome-back" class="nav-link" data-scroll-target="#welcome-back">Welcome back!</a></li>
  <li>
<a href="#r-packages" id="toc-r-packages" class="nav-link" data-scroll-target="#r-packages">R Packages</a>
  <ul class="collapse">
<li><a href="#open-your-posit-cloud-project" id="toc-open-your-posit-cloud-project" class="nav-link" data-scroll-target="#open-your-posit-cloud-project">Open Your Posit Cloud Project</a></li>
  <li><a href="#open-the-lab-2-r-markdown-file" id="toc-open-the-lab-2-r-markdown-file" class="nav-link" data-scroll-target="#open-the-lab-2-r-markdown-file">Open the Lab 2 R Markdown file</a></li>
  <li><a href="#into-the-tidyverse" id="toc-into-the-tidyverse" class="nav-link" data-scroll-target="#into-the-tidyverse">Into the Tidyverse</a></li>
  </ul>
</li>
  <li>
<a href="#types-of-variables" id="toc-types-of-variables" class="nav-link" data-scroll-target="#types-of-variables">Types of variables</a>
  <ul class="collapse">
<li><a href="#glimpsing-datasets" id="toc-glimpsing-datasets" class="nav-link" data-scroll-target="#glimpsing-datasets">Glimpsing Datasets</a></li>
  </ul>
</li>
  <li><a href="#pipes" id="toc-pipes" class="nav-link" data-scroll-target="#pipes">Pipes</a></li>
  <li>
<a href="#black-lives-matter" id="toc-black-lives-matter" class="nav-link" data-scroll-target="#black-lives-matter">Black lives matter!</a>
  <ul class="collapse">
<li><a href="#downloading-and-reading-the-data" id="toc-downloading-and-reading-the-data" class="nav-link" data-scroll-target="#downloading-and-reading-the-data">Downloading and reading the data</a></li>
  <li><a href="#creating-code-chunks" id="toc-creating-code-chunks" class="nav-link" data-scroll-target="#creating-code-chunks">Creating code chunks</a></li>
  <li><a href="#glimpsing-the-data" id="toc-glimpsing-the-data" class="nav-link" data-scroll-target="#glimpsing-the-data">Glimpsing the data</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data wrangling</a></li>
  </ul>
</li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/UGQuants/quants_workbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><section id="data-in-r" class="level1"><h1>Data in R</h1>
<section id="welcome-back" class="level2"><h2 class="anchored" data-anchor-id="welcome-back">Welcome back!</h2>
<p>In the previous lab, we set up an RStudio session in Posit Cloud and we got familiar with the RStudio environment and the purpose and contents of RStudio’s panes. In this Lab we will learn about R packages, how to install them and load them. We will also use different types of data. You will have the chance to practice with additional <code>R</code> operators. Lastly, we will load a real-world data set and put in practice your new skills.</p>
<div class="callout callout-style-simple callout-note callout-titled" title="Overview">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Overview
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this lab you will know how to:</p>
<ul>
<li>install and load packages in R</li>
<li>download a dataset from a URL and assign it to a named object</li>
<li>use the pipe (<code>|&gt;</code>) operator to chain steps</li>
<li>examine, wrangle, and subset a dataset using functions</li>
</ul>
</div>
</div>
</section><section id="r-packages" class="level2"><h2 class="anchored" data-anchor-id="r-packages">R Packages</h2>
<p>As mentioned in our last lab, <code>R</code> <span class="citation" data-cites="R-base">(<a href="#ref-R-base" role="doc-biblioref">R Core Team 2021</a>)</span> is a collaborative project. This means that <code>R</code> users are developing, maintaining, and extending the functionalities constantly. When you set up <code>R</code> and RStudio for the first time, as we did last week, it comes only with the ‘basic’ functionalities by default, sometimes referred to as ‘base R’. However, there are literally thousands of extensions that are developed by other users. In R, these non-default extensions are called <em><strong>packages</strong></em>.</p>
<p>Most of the time, we use packages because they simplify our work in <code>R</code> - such as by replacing what would take dozens of lines of complex code in base R with a simple one-line function - or they allow us to extend beyond the capabilities of base R.</p>
<p>Let’s install and load some useful packages. We will start with one of R’s most famous packages, and one we will use across the labs, the <code>tidyverse</code> <span class="citation" data-cites="R-tidyverse">(<a href="#ref-R-tidyverse" role="doc-biblioref">Wickham 2021</a>)</span> package.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> First, sign-in to Posit Cloud, create/open your Labs-1-2 project, and then open the Lab-2 R Markdown file.</p>
<section id="open-your-posit-cloud-project" class="level3"><h3 class="anchored" data-anchor-id="open-your-posit-cloud-project">Open Your Posit Cloud Project</h3>
<p>For those who missed Lab 1:</p>
<ol type="1">
<li>Make sure you have a free, institutional-subscription <a href="https://sso.posit.cloud/glasgow">Posit Cloud</a> account (in case you have not created one yet, please follow the guidance provided in <a href="./01-intro.html#setting-up-rstudio">Lab 1</a>);</li>
<li>If you enrolled before teaching started, you will have received an email with a link to join your lab group. If you joined the course after the start of teaching, you can find a link in your Lab Group’s forum on Moodle. You tutor will also be able to provide you with a link.</li>
<li>Follow the rest of the <a href="./01-intro.html#part-3-create-a-new-project">Lab 1</a> guidance in the ‘Create a New Project’ section.</li>
</ol>
<p>For those who already joined and created a project in Lab 1, log into <a href="https://sso.posit.cloud/glasgow">Posit Cloud</a> and:</p>
<ol type="1">
<li>From the left-hand menu, click “Lab Group ..” where “..” is your lab group number.</li>
<li>Within the main screen, click “Labs-1-2” to open the Posit Cloud project you created last week.</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/posit_cloud_lab2_open-project.png" class="img-fluid figure-img"></p>
<figcaption>Select your lab group space and then open ‘Labs-1-2’ project</figcaption></figure>
</div>
</section><section id="open-the-lab-2-r-markdown-file" class="level3"><h3 class="anchored" data-anchor-id="open-the-lab-2-r-markdown-file">Open the Lab 2 R Markdown file</h3>
<p>You will find your project in the same state as you left it last week. To open a tab for the Lab 2 R Markdown file, click to open ‘Lab-02.Rmd’ in the “Files” tab in the bottom-right pane.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/rstudio_lab2_rmd.png" class="img-fluid figure-img"></p>
<figcaption>Click ‘Lab-02.Rmd’ in the “Files” tab in the bottom-right pane</figcaption></figure>
</div>
<p>Within Lab 1, you may have noticed the <code>key: value</code> lines between two <code>---</code>. This is called <code>YAML</code>. YAML is a simple human-readable markup language for data serialization. It consists of what are referred to as <code>key-value pairs</code>. Within R Markdown, a YAML header can be included at the very top and must be <code>fenced</code> with the three hyphens, <code>---</code>, at start and end.</p>
<p>The R Markdown file for this lab has a couple more lines in the YAML header this time:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/rstudio_lab2_yaml.png" class="img-fluid figure-img"></p>
<figcaption>YAML block at top of Lab-02.Rmd</figcaption></figure>
</div>
<p><code>title</code> and <code>author</code> are self-explanatory, but make sure to replace <code>[your name here]</code> with your name, making sure to keep the quotation marks around it. Without the quotation marks, you will receive an error message when trying to knit. (Note: Don’t knit your file just yet anyway as it will result in an error message until you complete the sections below.)</p>
<p><code>date</code> can be any text. However, <code>format(Sys.time(), '%d/%m/%y')</code> is a nice single line of R code that runs when the file is knitted to retrieve the current date and formats it as dd/mm/yyyy, such as 12/09/2025. This then effectively makes the <code>date</code> field “date this file was knitted” and saves you having to manually update it each time.</p>
<p><code>output</code> specifies what file format(s) to output to when knitting the R Markdown file. Across the labs and assessments we are using ‘html_document’ as it is easiest to work with across the packages we are using in the labs and assessments.</p>
<p>After the YAML header, there is a ‘setup’ code chunk setting <code>knitr</code> options:</p>
<p><img src="./images/rstudio_lab2_setupchunk.png" class="img-fluid" alt="r setup code chunk with knitr options to set message and warmings to FALSE"><br></p>
<p>This may look intimidating, but it is relatively simple when parsed bit by bit:</p>
<ul>
<li>
<code>knitr</code> is the package used to knit R Markdown files</li>
<li>
<code><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">knitr::opts_chunk</a></code> is an object that stores default settings applied to all code chunks</li>
<li>
<code>knitr::opts_chunk$set(...)</code> runs the <code>set()</code> function to change the <code><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">knitr::opts_chunk</a></code> default settings</li>
</ul>
<p>So, what the code in the setup chunk does is set messages and warnings to “FALSE”. This prevents any messages or warnings that get raised when running code chunks from also appearing in any knitted files. (Why we do this will become clear in a bit.)</p>
<div class="callout callout-style-simple callout-caution callout-titled" title="R Operators">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Operators
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<code>::</code> is the <strong>namespace operator</strong> for accessing an object (such as a function or dataset) from a package, in the format <code>package::object</code>. If you load a package using the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function, as we will do later, you can call the object directly without <code>package::</code>.</li>
<li>
<code>$</code> is the <strong>component operator</strong> for accessing named elements within an object, in the format <code>object$component</code>. In data analysis it is often used to access a column (variable) from a data frame. For example, if a data frame named <code>df</code> has a column named <code>age</code>, you can access it with <code>df$age</code>.</li>
</ul>
</div>
</div>
</section><section id="into-the-tidyverse" class="level3"><h3 class="anchored" data-anchor-id="into-the-tidyverse">Into the Tidyverse</h3>
<ol type="1">
<li>Once you have the Lab 2 R Markdown file open, type the following in the Console (bottom-right pane) and hit ‘Enter’ to run it:</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tidyverse"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Wait until you get the message ‘The downloaded source packages are in …’. The install process can take a couple of minutes to finish.</li>
</ol>
<p><img src="./images/rstudio_lab2_tidyinstalled.png" class="img-fluid" alt="Console once tidyverse package finished installing">/</p>
<ol start="3" type="1">
<li>Once the package is installed, you next need to load it using the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function. In the <code>preamble</code> code chunk already setup in the R Markdown file, add the following in the line under the <code># Load packages</code> comment:</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Now run the code chunk. Either by pressing <code>Ctrl+Shift+Enter</code> with your text cursor within the code chunk, or by clicking the green triangle in the top-right of the code chunk.</li>
</ol>
<p><img src="./images/rstudio_lab2_library.png" class="img-fluid" alt="Run code chunk to load the tidyverse package"><br></p>
<p>And that’s it, <code>tidyverse</code> is ready to use in your current session!</p>
<p>Note, we run <code>install.packages("package_name")</code> in the Console as we only need to install the package once for each Posit Cloud project. We load packages with <code><a href="https://rdrr.io/r/base/library.html">library(package_name)</a></code> in a code chunk at the top of the R Markdown file as packages need to be loaded for every R session. If we ran <code><a href="https://rdrr.io/r/base/library.html">library(...)</a></code> in the Console instead of adding it to a code chunk, our packages would not be available in the fresh R session that is created when knitting and would result in an error message.</p>
<p>Another thing to note is that when you install a package, you need to use quotation marks, <code>install.packages("package_name")</code>, whereas when loading a package you just use the package name without quotation marks, <code><a href="https://rdrr.io/r/base/library.html">library(package_name)</a></code>.</p>
<p>What you may also notice is the message raised in the Console when loading the tidyverse. (If you already ran the setup code chunk you won’t see any text). This is one of the reasons why we have the setup chunk to exclude messages and warnings in knitted files. If we knitted the Lab-02.Rmd file without the setup chunk, the text on loading the tidyverse would also appear in the knitted HTML file after the preamble chunk. We will cover other options you can set to customise what appears in your knitted files in later weeks.</p>
<p><img src="./images/rstudio_lab2_messages.png" class="img-fluid" alt="Text shown in knitted file if warnings were not set to FALSE"><br></p>
<p>This text often causes users new to R to think an error has occurred. However, it is merely a ‘message’ about conflicts that can be ignored.</p>
<p>The tidyverse is a <code>meta package</code> that bundles a collection of packages together, such as <code>dplyr</code> and <code>ggplot2</code>. These packages share a common design philosophy and are often used together in data analysis. Loading the tidyverse meta package, <code><a href="https://tidyverse.tidyverse.org">library(tidyverse)</a></code>, saves us from having to load each of these packages individually with <code><a href="https://dplyr.tidyverse.org">library(dplyr)</a></code>, <code><a href="https://ggplot2.tidyverse.org">library(ggplot2)</a></code>, and so on.</p>
<p>What the message is showing then is that each of the core tidyverse packages were loaded OK, and there are conflicts for functions provided by the <code>dplyr</code> package. Two of its functions, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lag()</a></code>, share the same name as functions in the base R <code>stats</code> package. After loading the tidyverse, any code calling <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> will use the <code>dplyr</code> function with that name rather than the <code>stats</code> ones. (This applies only to <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> directly, the stats function can still be accessed when the tidyverse is loaded by using the <code>::</code> namespace operator, <code><a href="https://rdrr.io/r/stats/filter.html">stats::filter()</a></code>.)</p>
<div class="callout callout-style-simple callout-tip callout-titled" title="New Terms">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
New Terms
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<code>tidyverse</code>: a collection of R packages that share a consistent design philosophy and work together for importing, wrangling, and visualising data.</li>
<li>
<code>YAML</code>: a human-readable data serialisation language, often used for configuration/settings; in R Markdown the YAML front matter between <code>---</code> sets document metadata and other options.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled" title="`library()` function">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function
</div>
</div>
<div class="callout-body-container callout-body">
<p>Loads an installed package so its functions are available in the R session.</p>
<p><strong>Usage:</strong> <code><a href="https://rdrr.io/r/base/library.html">library(package_name)</a></code></p>
<p><strong>Notes:</strong></p>
<ul>
<li>A package needs to be installed first using <code>install.packages("package_name")</code> in the Console.</li>
<li>It is best practice to load packages in a code chunk at the top of R Markdown files.</li>
</ul>
</div>
</div>
</section></section><section id="types-of-variables" class="level2"><h2 class="anchored" data-anchor-id="types-of-variables">Types of variables</h2>
<p>In quantitative analysis, we often distinguish two main types of variables:</p>
<ol type="1">
<li>
<strong>Numeric variables</strong> have values that describe measurable or countable quantities.
<ul>
<li>
<strong>Continuous variables</strong> have values that can fall anywhere within a range, such as time and speed.</li>
<li>
<strong>Discrete variables</strong> have values that are whole numbers that count something, such as number of children in a household.</li>
</ul>
</li>
<li>
<strong>Categorical variables</strong> have values that describe distinct, mutually exclusive categories.
<ul>
<li>
<strong>Nominal variables</strong> have categories without any order, such as country, name, political party, and gender.</li>
<li>
<strong>Ordinal variables</strong> have categories with a meaningful order, such as education level or level of satisfaction.</li>
</ul>
</li>
</ol>
<p>In R, the most basic data building blocks are <strong>atomic vectors</strong>. There are six atomic <em>types</em>: <code>logical</code>, <code>integer</code>, <code>double</code>, <code>character</code>, <code>complex</code>, and <code>raw</code>.</p>
<p>In relation to our two main types of variables, we use the following vectors:</p>
<ul>
<li>
<strong>Numeric vectors</strong> (<code>integer</code> or <code>double</code>) to store continuous and discrete values.</li>
<li>
<strong>Factor vectors</strong> (a <code>class</code> built on <code>integer</code> codes + <code>character</code> labels) to store nominal and ordinal categorical values.</li>
</ul>
<p>A numeric vector is usually stored as a <code>double</code> internally by default. The difference between <code>integer</code> and <code>double</code> is based on how they are computationally stored. Base R and most R packages handle the difference behind the scenes, so the difference in how they are stored does not matter to us.</p>
<p>A factor is a class combining <code>integer</code> codes and a <code>levels</code> attribute containing the human-readable <code>character</code> labels for those codes. Each stored integer points to a character label in <code>levels</code>, so <code>1</code> might correspond to <code>"Conservative"</code>, <code>2</code> might correspond to <code>"Labour"</code>, and so on. For ordered factors, used for ordinal variables, R also records an explicit order of the levels to enable comparisons and sorting by that order.</p>
<p>Two other vectors we commonly use are:</p>
<ul>
<li>
<strong>Character vectors</strong> (<code>character</code>) to store text, such as unique respondent IDs (“A102”, “C006”) and free-text answers.</li>
<li>
<strong>Logical vectors</strong> (<code>logical</code>) to store boolean <code>TRUE</code> / <code>FALSE</code> values, useful for filtering and conditions, such as <code>age &gt; 30</code>.</li>
</ul>
<p>In R, there are couple of functions that will help us to identify the type of data. First, we have <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code>. This prints some of the main characteristics of a data set, namely its overall dimension, name of each variable (column), the first values for each variable, and the type of the variable. Second we have the function <code><a href="https://rdrr.io/r/base/class.html">class()</a></code>, that will help us to determine the overall class(type) of on <code>R</code> object.</p>
<div class="callout callout-style-simple callout-caution callout-titled" title="`glimpse()`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>From the <code>dplyr</code> package, and loaded with the <code>tidyverse</code> package. Provides a ‘glimpse’ of an object.</p>
<p><strong>Usage</strong>: <code>glimpse(x)</code></p>
<p><strong>Arguments</strong>:</p>
<ul>
<li>
<code>x</code> - The object (usually a data frame / tibble) to glimpse.</li>
</ul>
<p><strong>Returns</strong>: Prints to the Console. For data frames / tibbles, it shows counts for rows and columns and a compact, transposed preview showing column names, types, and a few example values.</p>
<p><strong>Notes</strong>:</p>
<ul>
<li>A tibble is just a tidyverse version of base R’s data frames that has some nice extras.</li>
<li>Shows types such as <code>&lt;int&gt;</code> (integer), <code>&lt;dbl&gt;</code> (double), <code>&lt;chr&gt;</code> (character), <code>&lt;lgl&gt;</code> (logical), <code>&lt;fct&gt;</code> (factor).</li>
</ul>
</div>
</div>
<section id="glimpsing-datasets" class="level3"><h3 class="anchored" data-anchor-id="glimpsing-datasets">Glimpsing Datasets</h3>
<p>We are now going to use some datasets that are available to us in the <code>R</code> session. <code>R</code> comes with some example datasets out of the box, such as <code>iris</code> with 150 observations of iris flowers. Some R packages also include additional example datasets, such as <code>starwars</code> - included in the <code>dplyr</code> tidyverse package - with info about 87 Star Wars characters. Unlike other datasets that we have to manually load, and will cover in later section, we can access these in any R session out the box or after loading the relevant package that provides them.</p>
<p>Please go to the ‘Types of variables’ section in your <code>Lab-02.Rmd</code> file. You will see a few code chunks already setup for you:</p>
<ol type="1">
<li>We will start with a classic dataset example in R called <code>iris</code>. (For more info about the dataset, you can type <code><a href="https://rdrr.io/r/datasets/iris.html">?iris</a></code> or <code><a href="https://rdrr.io/r/datasets/iris.html">help(iris)</a></code> in the Console). Please go to the “iris-glimpse” code chunk in your R Markdown file and run it.</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">iris</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 5
$ Sepal.Length &lt;dbl&gt; 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.…
$ Sepal.Width  &lt;dbl&gt; 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.…
$ Petal.Length &lt;dbl&gt; 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.…
$ Petal.Width  &lt;dbl&gt; 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.…
$ Species      &lt;fct&gt; setosa, setosa, setosa, setosa, setosa, setosa, setosa, s…</code></pre>
</div>
</div>
<p>What do you observe from the output?</p>
<p>First, it tells you the number of rows and the columns on the top. After, it lists the name of each variable. Additionally, it tells you the type of the variable between these symbols <code>&lt; &gt;</code>. The first five variables in this dataset are of type <code>&lt;dbl&gt;</code> (double) which as covered above is a type of numeric variable. The last, <code>Species</code>, is a factor <code>&lt;fct&gt;</code>. So, for each of the 150 iris flowers observed, there is information on its species and four types of continuous measures. Though, as glimpse only provides a preview, we only see the values for the first few observations.</p>
<ol start="2" type="1">
<li>Now you know that each iris flower belongs to a species, but what are the specific categories in this data set? To find out, add the following in the ‘iris-levels’ code chunk and then run it.</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">iris</span><span class="op">$</span><span class="va">Species</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(If you receive ‘NULL’ when running the chunk, it because you have <strong>s</strong>pecies and not <strong>S</strong>pecies.)</p>
<p>As you can see, there are three categories, or <code>levels</code> as they are called in R factor variables, which are three types of iris flower species. Notice here we used the <code>$</code> component operator mentioned earlier. Here it basically means, from the iris data frame select the Species column/variable. <code><a href="https://rdrr.io/r/base/levels.html">levels()</a></code> is then a nice little utility function that shows all the levels for a column given to it as an argument.</p>
<!-- Let's move to a different data set. This time we will use another classic example called `diamonds`. This data set contains some characteristics of more than 50K pieces of diamonds (to get more information type `?diamonds` in your console). -->
<!-- 1. Let's glimpse at the `diamonds` data by running this line in your console. -->
<!-- ```{r eval=FALSE} -->
<!-- glimpse(diamonds) -->
<!-- ``` -->
<!-- 2. What can you observe?...Yes, this time we do not have factor columns, but we have `<ord>` in cut, colour and clarity, which means these are ordinal vectors. Now look at the levels of cut: -->
<!-- ```{r eval=FALSE} -->
<!-- levels(diamonds$cut) -->
<!-- ``` -->
<!-- 3. As you can see, there are five types of cut in this data set. You can even go further and find out how many diamond pieces are of each type by running this line: -->
<!-- ```{r eval=FALSE} -->
<!-- table(diamonds$cut) -->
<!-- ``` -->
<p>Now, let’s get serious and explore Star Wars.</p>
<p>The <code>starwars</code> data set from the <code>dplyr</code> package contains information about the characters, including height, hair colour, and sex. (Again, to get more information run <code><a href="https://dplyr.tidyverse.org/reference/starwars.html">?starwars</a></code> or <code><a href="https://dplyr.tidyverse.org/reference/starwars.html">help(starwars)</a></code> in the Console). For the purpose of keeping things relatively simple to focus on variable types, we will use a reduced version of the full data set.</p>
<ol type="1">
<li>First, run the ‘starwars-glimpse’ code chunk to create a reduced version of the data set named <code>starwars2</code> and then glimpse the Star Wars characters in that reduced data set:</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">starwars2</span> <span class="op">&lt;-</span> <span class="va">starwars</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">11</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">starwars2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, creating a reduced version uses another selection operator available with tibbles - the tidyverse’s version of an R data frame. The basic format is <code>dataset[rows, columns]</code>. Here <code>starwars[, 1:11]</code> leaves rows blank, which effectively means select all rows, and columns has <code>1:11</code>, which means select columns 1 to 11. So, the code returns all rows but only the first 11 columns.</p>
<p>What do you observe this time?</p>
<p>It seems that the data type is not consistent with their content. For example, the variables <code>species</code>, <code>gender</code>, and <code>hair_color</code> are of type <code>&lt;chr&gt;</code> (that is <code>character</code>), when according to what we covered above these should be factors. To transform them, we will use the function ´factor()´. This process is known as <strong>coercing</strong> a variable, that is when you change a variable from one type to another. <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> is another nice little helper function</p>
<!-- 3. Look what happens if you do the this..It confirms that this variable is stored as a character: -->
<!-- ```{r eval=FALSE} -->
<!-- class(starwars2$species) -->
<!-- ``` -->
<!-- 5. What if we first call the `factor()` function and then we ask R again about the type of vector using `class()` -->
<!-- ```{r eval=FALSE} -->
<!-- factor(starwars2$species) %>% class() -->
<!-- ``` -->
<ol start="2" type="1">
<li>Let’s coerce the species variable from character to factor and assign the result to the same column in the dataset. Add the following to the ‘starwars-factor’ code chunk and run it.</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">starwars2</span><span class="op">$</span><span class="va">species</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">starwars2</span><span class="op">$</span><span class="va">species</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, most objects in R are what is known as <code>immutable</code>, meaning any changes to them requires explicit assignment back to the object. If you run <code>factor(starwars2$species</code> on its own, it will return all the values for <code>species</code> and the levels created. However, for the species column to be updated with the results returned by <code>factor(starwars2$species)</code> we need the <code>starwars2$species &lt;- ...</code> assignment as well.</p>
<ol start="3" type="1">
<li>Let’s check if the type of variable really changed by glimpsing the data and checking the levels of <code>species</code>. Added the following to the ‘starwars-glimpse2’ chunk and run it.</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">starwars2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">starwars2</span><span class="op">$</span><span class="va">species</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The glimpse result now is telling us that <code>species</code> is a <code>&lt;fct&gt;</code>, as expected. Furthermore, the <code><a href="https://rdrr.io/r/base/levels.html">levels()</a></code> function reveals that there are 37 types of species, including Human, Ewok, Droid, and more.</p>
<p>Hopefully, these examples will help you to identify the main vector types and, more importantly, an initial understanding of how to coerce them into an appropriate type. Be aware that many data sets represent categories with numeric values without the labels, for example, using ‘0’ for male and ‘1’ for female. Usually, large data sets are accompanied by extra information in a <em>code book</em> or <em>documentation</em> file, which specifies the values for the numeric code and their respective meaning. It’s important to read the code book/documentation of every data set as the conventions and meanings can vary. For example, some surveys now put gender in alphabetical order, with 0 for female and 1 for male.</p>
</section></section><section id="pipes" class="level2"><h2 class="anchored" data-anchor-id="pipes">Pipes</h2>
<!-- More operators and symbols...Let's start with the hashtag `#`. Even though this is not an operator in R, this symbol allow us to include a comment or ´mute´ the whole line in your script. In fact, it is important that you add comments on your own code, so when you come back later to your code, you can have a quicker idea of what it is going in each line of the script. -->
<!-- The dollar sign `$` is frequently used and it is part of base R. Actually, we used it a couple of times in the previous section. This is used to access or extract information from an object (e.g. a data set). For instance, earlier we selected only one variable from the `starwars` data set by writing `starwars2$species`. A practical tip to quickly access or find variables in a data set is to write the name of your object followed by the dollar sign only, like this: `starwars2$` (without specifying the variable to be accessed yet). After, type `tab` in your keyboard. Then, R will display a list with the variables available. Try it yourself! -->
<p>A useful operator is the pipe <code>|&gt;</code>. This is the base R version of the pipe. This operator is what is known in programming as <code>syntactic sugar</code>. It is syntax which helps make code easier to read and write without changing any functionality. The pipe operator passes the result of one function as the first argument to the next (left to right).</p>
<p>Run the ‘pipe-1’ code chunk and check its results.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">1</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="fl">1</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> function adds the value of two numbers in format <code>sum(x, y)</code>. Using a pipe for <code>1 |&gt; sum(1)</code> is the equivalent to <code>sum(1, 1)</code>. So for line one it is equivalent of ‘take 1, then add it with 1’ and line 2 ‘take 1, then add it with 1, then add it with 5’.</p>
<p>This may seem as if it is overcomplicating things, but as the code becomes more complex the value of the pipe operator becomes clearer. The second line, <code>1 |&gt; sum(1) |&gt; sum(5)</code> would be written as <code>sum(sum(1,1), 5)</code> without pipes. Going left to right, <code>1 |&gt; sum(1)</code> would be <code>sum(1,1)</code> and then <code>sum(1,1) |&gt; sum(5)</code> would be <code>sum(sum(1,1), 5)</code>. Pipes then help us avoid <code>function(function(function(...), ...) ...)</code> monstrosities in our code.</p>
<p>Note, in the readings and other materials, you may come across another <code>%&gt;%</code> pipe. This pipe comes from the <code>tidyverse</code>. The tidyverse pipe came before the base R one, where due to its popularity an equivalent was added to base R. Whilst you will still see it in use, and it remains supported in the tidyverse, the tidyverse itself recommends people start using the base R <code>|&gt;</code> pipe. To see that they work the same, run the ‘pipe-2’ chunk.</p>
</section><section id="black-lives-matter" class="level2"><h2 class="anchored" data-anchor-id="black-lives-matter">Black lives matter!</h2>
<p>In this section we will work with data originally collected by The Guardian in 2015, for more information click <a href="https://www.theguardian.com/us-news/ng-interactive/2015/jun/01/about-the-counted">here</a>. The data set we will use today is an extended version which was openly shared in GitHub by the American news website <a href="https://fivethirtyeight.com/">FiveThirtyEight</a>. This data set contains information about the people that were killed by police or other law enforcement bodies in the US, such as age, gender, race/ethnicity, etc. Additionally, it includes information about the city or region where the event happened. For more information click <a href="https://github.com/fivethirtyeight/data/tree/master/police-killings">here</a>.</p>
<section id="downloading-and-reading-the-data" class="level3"><h3 class="anchored" data-anchor-id="downloading-and-reading-the-data">Downloading and reading the data</h3>
<p>As with installing packages, we only want to download the data once. For this lab, we will download the data running code in the Console. Next week though, we will go through how to set up an R script for downloading data. This is a common strategy for sharing the code used to download data whilst still keeping it separate to your main R Markdown file.</p>
<p>First, we will create a new folder in our project directory to store the data. To do it from the Console, run this line. (Don’t worry if you get a warning. This appears because you already have a folder with this name):</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="st">"data"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in the ‘Files’ tab of Pane 4, the bottom-right pane, there is a new folder called <code>data</code>.</p>
<p><img src="./images/rstudio_lab2_data-folder.png" class="img-fluid" alt="Files tab showing the newly created ‘data’ folder."><br></p>
<p>Now, download the data from the GitHub repository using the function <code><a href="https://rdrr.io/r/utils/download.file.html">download.file()</a></code>. This function takes two arguments separated by a comma: (1) the URL and (2) the destination (including the directory, file name, and file extension), as shown below.</p>
<p>Copy and paste the following lines into the Console:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/download.file.html">download.file</a></span><span class="op">(</span><span class="st">"https://github.com/fivethirtyeight/data/raw/master/police-killings/police_killings.csv"</span>, <span class="st">"data/police_killings.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(Note, to avoid any issues typing out the URL, you can click the clipboard icon in the top-right of the code above to copy the full contents to your clipboard.)</p>
<p>After that, we are ready to read the data. As the data comes as a <code>.csv</code> file, we can use the <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> function included in the <code>tidyverse</code> package (make sure you the package is loaded in your session as explained in a <a href="#installing-packages">previous section</a>).</p>
<p>We will assign the data in an object called <code>police</code>. Importantly, as with loading packages, when loading data it is good practice to do so at the top of the file. So, go all the way back up to the preamable code chunk and add the following line after the ‘# Read data’ comment.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">police</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/police_killings.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You should now have:</p>
<p><img src="./images/rstudio_lab2_preamble2.png" class="img-fluid" alt="Preamble chunk with line added to read csv file."><br></p>
<p>Run the code chunk and you’ll know it has run OK if can see ‘police’ in your Global Environment in the top-right pane. It will have 467 observations and 34 variables (columns).</p>
<p><img src="./images/rstudio_lab2_env.png" class="img-fluid" alt="‘police’ object listed in Global Environment."><br></p>
</section><section id="creating-code-chunks" class="level3"><h3 class="anchored" data-anchor-id="creating-code-chunks">Creating code chunks</h3>
<p>OK, before we look at this police data, a reminder about creating code chunks. Scroll back in your R Markdown file to “## Black lives matter!”. For this section, you will need to create your own code chunks.</p>
<p>To create a new code chunk, you have four options:</p>
<ul>
<li>Put your text cursor on a line in your R Markdown file and press <code>Ctrl+Alt+I</code> on the keyboard.</li>
<li>From the menu bar at the top of RStudio, you can select <code>Code &gt; Insert Chunk</code>.</li>
<li>Manually type three backticks, on UK layout keyboards the key to the left of the 1 key, and then <code>{r}</code> (remember to add three backticks on a line below to close the code chunk as well).</li>
<li>Click on the icon that is a c in green square with a ‘+’ in a circle in top-left corner, and then click on R to create an R code chunk.</li>
</ul>
<p><img src="./images/rstudio_lab2_new-chunk.png" class="img-fluid" alt="Using the ‘c’ icon to create a new code chunk."><br></p>
<p>By default, a new code chunk will be plain <code>{r}</code>, but you can edit this to give it an optional name:</p>
<p><img src="./images/rstudio_lab2_optional-name.png" class="img-fluid" alt="Adding ‘optional-name’ to R code chunk."><br></p>
</section><section id="glimpsing-the-data" class="level3"><h3 class="anchored" data-anchor-id="glimpsing-the-data">Glimpsing the data</h3>
<p>Back to the data. Let’s first glimpse the <code>police</code> data. Create a code chunk then add and run the following:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">police</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, there are several variables included in the dataset, such as age, gender, law enforcement agency (<code>lawenforcementagency</code>), or whether the victim was armed (<code>armed</code>). You will see some of these variables are not in the appropriate type. For instance, some are categorical and should be a factor (<code>&lt;fct&gt;</code>) instead of character (<code>&lt;chr&gt;</code>).</p>
</section><section id="data-wrangling" class="level3"><h3 class="anchored" data-anchor-id="data-wrangling">Data wrangling</h3>
<p>Before coercing these variables, we will create a smaller subset selecting only the variables that we are interested in. To do so, we can use the <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> function. The <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> function takes the name of the data first and then the name of the variables we want to keep (no quotation marks needed). We will select a few variables and assign the result to a new object called <code>police_2</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">police_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">police</span>, <span class="va">age</span>, <span class="va">gender</span>, <span class="va">raceethnicity</span>, <span class="va">lawenforcementagency</span>, <span class="va">armed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> is another function from the <code>dplyr</code> tidyverse package. Many tidyverse functions that take a data frame as the first argument, <code>select(first_argument, ...)``, will assume all variables listed after are from that data frame. Within the function, this then let's us type</code>age<code>and</code>gender<code>rather than</code>police<span class="math inline">\(age` and `police\)</span>gender`.</p>
<p>If you look again to the ‘Environment’ tab, there is now a second data set with the same number of observations but only 5 variables. Create a new code chunk, then add and run the following code to glimpse its contents.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">police_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having a closer look at the reduced version, we can see that in fact all the variables are of type <code>&lt;chr&gt;</code> (character), including <code>age</code>.</p>
<p>Let’s coerce the variables in to their correct type. Start by creating a code chunk and naming it ‘coerce-police_2’ or similar.</p>
<p>Then within the chunk, let’s start with age, coercing it from character to numeric by adding the following lines:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Coerce numeric</span></span>
<span><span class="va">police_2</span> <span class="op">&lt;-</span> <span class="va">police_2</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code># Coerce numeric</code> line let’s us add a comment to our code. Any R code after a <code>#</code> is treated as a comment and is not run as part of the code. This is useful for recording the ‘why’ behind the code, so future-you (and others) can quickly read and understand it.</p>
<p>(You may be wondering why outside the code chunks there are <code>#</code> but these become headers when knitting the document. The reason is within Markdown syntax <code>#</code> is used for Headings, and Heading level - <code>#</code> for Heading 1, <code>##</code> for Heading 2, and so on. Unfortunately, as R and Markdown developed separately before the creation of R Markdown bringing them together, they both had by that point decided to use <code>#</code> for different things. Whilst confusing at first, it all boils down to inside chunk = comments, outside chunk = header. The reason for <code>##</code> Heading 2 for all the headings in the R Markdown template for this lab is because Heading 1 is already used for the title - the <code>title: "..."</code> in the YAML header.)</p>
<p>Age is not known for some cases. Thus, it is recorded as ‘Unknown’ in the dataset. Since this is not recognized as a numeric value in the coercion process, <code>R</code> automatically sets it as a missing value, <code>NA</code>. This is why it will give you a warning message. (You will not see a warning message if you ran the knitr setup chunk that disabled warning messages.)</p>
<p>We can continue coercing <code>raceethnicity</code> and <code>gender</code> from character to a factor by adding the following lines to our chunk:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Coerce factor</span></span>
<span><span class="va">police_2</span> <span class="op">&lt;-</span> <span class="va">police_2</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>raceethnicity <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">raceethnicity</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">police_2</span> <span class="op">&lt;-</span> <span class="va">police_2</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>gender <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Run the chunk and then create and run a new chunk with the following to glimpse the data frame again:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">police_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You should hopefully now see the three coerced variables now have the correct types:</p>
<ul>
<li>
<code>age</code> as numeric <code>&lt;dbl&gt;</code>
</li>
<li>
<code>gender</code> and <code>raceethnicity</code> as factor <code>&lt;fct&gt;</code>
</li>
</ul>
<p>Now, let’s run a summary of your data. This shows the number of observations in each category or a summary of a numeric variable. Create a code chunk, then add and run the following:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">police_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are some interesting figures coming out from the summary. For instance, in age you can see that the youngest (Min.) is… 16 years old(?!), and the oldest (Max.) 87 years old. Also, the vast majority are male (445 vs 22). In relation to race/ethnicity, roughly half are ‘White’, whereas ‘Black’ individuals represent an important share. One may question the proportion of people killed in terms of race/ethnicity compared to the composition of the total population (considering Black is a minority group in the US).</p>
<p>Let’s suppose that we only want observations in which race/ethnicity is not unknown. To ‘remove’ <em>undesired</em> observation we can use the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> function. Remember, to make changes to an object we need to assign the result of a function back to it. We will then need to assign the result of <code>filter</code> back to the <code>police_2</code> object.</p>
<p>Create a chunk, then add and run the following:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">police_2</span> <span class="op">&lt;-</span> <span class="va">police_2</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">raceethnicity</span> <span class="op">!=</span> <span class="st">"Unknown"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So, what just happened in the code above? First, the pipe operator, <code>|&gt;</code>: What we are doing verbally is <em>take the object <code>police_2</code>, THEN filter raceethnicity based on a condition</em>.</p>
<p>Then, what is happening inside the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> function? Let’s have a look at what <code>R</code> does in the background for us (Artwork by @alison_horst):</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/lab_2_filter.jpg" class="img-fluid figure-img"></p>
<figcaption>Filter. Source: Artwork by <span class="citation" data-cites="Horst">Horst (<a href="#ref-Horst" role="doc-biblioref">n.d.</a>)</span>.</figcaption></figure>
</div>
</div>
</div>
<p>Note, <code>df</code> for us is <code>police_2</code>. Since we are using the pipe operator, <code>police_2 |&gt; filter(raceethnicity != "Unkown")</code> is equivalent to writing <code>filter(police_2, raceethnicity != "Unkown"</code>) without the pipe operator.</p>
<p>In our example then, we are keeping the observations in <code>raceethnicity</code> that are NOT EQUAL (<code>!=</code>) to ‘Unknown’. When we then assign the result to an object named the same as our existing object, we replace the <em>old</em> dataset with the new filtered version.</p>
<p>Finally then, create another code chunk to get a glimpse and summary of the data frame again:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">police_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 452
Columns: 5
$ age                  &lt;dbl&gt; 16, 27, 26, 25, 29, 29, 22, 35, 44, 31, 76, 40, N…
$ gender               &lt;fct&gt; Male, Male, Male, Male, Male, Male, Male, Male, M…
$ raceethnicity        &lt;fct&gt; Black, White, White, Hispanic/Latino, White, Whit…
$ lawenforcementagency &lt;chr&gt; "Millbrook Police Department", "Rapides Parish Sh…
$ armed                &lt;chr&gt; "No", "No", "No", "Firearm", "No", "No", "Firearm…</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">police_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age           gender                   raceethnicity lawenforcementagency
 Min.   :16.00   Female: 20   Asian/Pacific Islander: 10   Length:452          
 1st Qu.:28.00   Male  :432   Black                 :135   Class :character    
 Median :35.00                Hispanic/Latino       : 67   Mode  :character    
 Mean   :37.15                Native American       :  4                       
 3rd Qu.:45.00                Unknown               :  0                       
 Max.   :87.00                White                 :236                       
 NA's   :2                                                                     
    armed          
 Length:452        
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
</div>
<p>To make it easier to compare, the results from this code are included here as well. Within your R Markdown file, scroll up to your previous glimpse and summary chunks for the <code>police_2</code>. You should see that under <code>raceethnicity</code>, ‘Unkown’ is now 0 instead, when it was 15 before we filtered the dataset. Correspondingly, the total number of rows has dropped by 15, going from 467 initially, to 452 after filtering.</p>
<!-- Finally, there are times when you would like to group categories in a factor differently, for example to simplify a graph or statistical analysis. Coming back to race/ethnicity, we may observe that there are some relatively small categories, e.g. 'Native American', 'Asian/Pacific Islander'. So we will create a new variable called `raceethnicity_recoded` using `mutate()` which will recode these categories in to one only called 'Other' using the function `recode()`. We will save the result under the same data named `police_2`. -->
<!-- ```{r eval = FALSE} -->
<!-- police_2 <- police_2 %>%  -->
<!--   mutate(raceethnicity_recoded = recode(raceethnicity, -->
<!--                                         'Asian/Pacific Islander' = 'Other',  -->
<!--                                         'Native American' = 'Other')) -->
<!-- ``` -->
<!-- If we look at the summary again, the classifications of `raceethnicity` are reduced in the new variable `raceethnicity_recoded`. The categories 'Native American' and 'Asian/Pacific Islander' were summed in only one category called `Other`. -->
</section></section><section id="activities" class="level2"><h2 class="anchored" data-anchor-id="activities">Activities</h2>
<p>Discuss the following questions with your neighbour or tutor:</p>
<ol type="1">
<li>What is the main purpose of the functions <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> and <code>filter</code>?</li>
<li>What does <em>coerce</em> mean in the context of <code>R</code>? and Why do we need to coerce some variables?</li>
<li>What is the <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> function useful for?</li>
</ol>
<p>Using the <code>police_2</code> dataset:</p>
<ol type="1">
<li>Filter how many observations are ‘White’ in <code>raceethnicity</code>? How may rows/observations are left?</li>
<li>How many ‘Hispanic/Latino’ are there in the dataset?</li>
<li>Using the example of Figure 2.3, could you filter how many were killed that were (a) ‘Black’ and (b) killed by firearm (‘firearm’)?</li>
<li>What about ‘White’ and ‘firearm’?</li>
</ol>
<p>Extra activities:</p>
<ol type="1">
<li>Why did you have to use quotes in the following: <code>filter(police, raceethnicity==”White” &amp; raceethnicity==”firearm”)</code>?</li>
<li>What do you have to repeat the variable <code>raceethnicity</code> twice?</li>
</ol>
<p>This is the end of Lab 2. Again, the changes in your R Markdown file should be saved automatically in RStudio. However, make sure this is the case as covered in Lab 1. After this, you can close the tab in your web browser. Hope you had fun!</p>



</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Horst" class="csl-entry" role="listitem">
Horst, Alison. n.d. <span>“<span>GitHub</span> - Allisonhorst/Stats-Illustrations: <span>R</span> &amp; Stats Illustrations by @Allison_horst.”</span> Accessed July 11, 2022. <a href="https://github.com/allisonhorst/stats-illustrations">https://github.com/allisonhorst/stats-illustrations</a>.
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. 2021. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-R-tidyverse" class="csl-entry" role="listitem">
Wickham, Hadley. 2021. <em>Tidyverse: Easily Install and Load the Tidyverse</em>. <a href="https://CRAN.R-project.org/package=tidyverse">https://CRAN.R-project.org/package=tidyverse</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p><a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ugquants\.github\.io\/quants_workbook\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./01-intro.html" class="pagination-link" aria-label="**Lab 1** Introduction to R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><strong>Lab 1</strong> Introduction to R</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-Lab3.html" class="pagination-link" aria-label="**Lab 3** Data Wrangling">
        <span class="nav-page-text"><strong>Lab 3</strong> Data Wrangling</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/UGQuants/quants_workbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Licensed under <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <i class="fa-brands fa-creative-commons-sa" aria-label="creative-commons-sa"></i> <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0</a></p>
</div>
  </div>
</footer>


</body></html>