<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>lab8 – Lab Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-Lab9.html" rel="next">
<link href="./07-Lab7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8eac3228050af7a73983e45baba5544d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-c1e19c279b1c7e82165a3f66195d40d3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-8eac3228050af7a73983e45baba5544d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="css/nav-toggle.css">
</head>
<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./brand/uofg-keyline.png" alt="" class="navbar-logo light-content"><img src="./brand/uofg-keyline.png" alt="" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lab Workbook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="./assessments/assessments.html"> 
<span class="menu-text">Assessments</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/UGQuants/quants_workbook" title="Workbook GitHub" class="quarto-navigation-tool px-1" aria-label="Workbook GitHub"><i class="bi bi-github"></i></a>
    <a href="./#" title="" class="quarto-navigation-tool px-1" aria-label="Toggle navbar (Alt+Shift+H)"><i class="bi bi-pin-fill"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"></h1>
        </a>     
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 1</strong> Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Lab2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 2</strong> Data in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Lab3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 3</strong> Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Lab4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 4</strong> Exploratory Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Lab5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 5</strong> Reporting in R Markdown</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Lab6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 6</strong> Visual Exploratory Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Lab7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 7</strong> Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Lab8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><strong>Lab 8</strong> Simple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Lab9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 9</strong> Multiple Linear Regression (part 1)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Lab10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 10</strong> Multiple Linear Regression (part 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Lab11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Lab 11</strong> Interpretive Report Assessment</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Answers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workbook suggested answers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link active" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
<li><a href="#welcome" id="toc-welcome" class="nav-link" data-scroll-target="#welcome">Welcome</a></li>
  <li>
<a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
<li><a href="#r-markdown" id="toc-r-markdown" class="nav-link" data-scroll-target="#r-markdown">R Markdown</a></li>
  <li><a href="#dataframe-setup" id="toc-dataframe-setup" class="nav-link" data-scroll-target="#dataframe-setup">Dataframe Setup</a></li>
  </ul>
</li>
  <li>
<a href="#viewing-trends" id="toc-viewing-trends" class="nav-link" data-scroll-target="#viewing-trends">Viewing Trends</a>
  <ul class="collapse">
<li><a href="#scatter-plots" id="toc-scatter-plots" class="nav-link" data-scroll-target="#scatter-plots">Scatter Plots</a></li>
  <li><a href="#was-this-a-good-guess" id="toc-was-this-a-good-guess" class="nav-link" data-scroll-target="#was-this-a-good-guess">Was this a good guess?</a></li>
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals">Residuals</a></li>
  </ul>
</li>
  <li>
<a href="#key-this-and-expand---could-work-as-initial-return-to-example-from-last-week" id="toc-key-this-and-expand---could-work-as-initial-return-to-example-from-last-week" class="nav-link" data-scroll-target="#key-this-and-expand---could-work-as-initial-return-to-example-from-last-week">KEY THIS AND EXPAND - could work as initial return to example from last week</a>
  <ul class="collapse">
<li><a href="#using-a-linear-model" id="toc-using-a-linear-model" class="nav-link" data-scroll-target="#using-a-linear-model">Using a Linear Model</a></li>
  </ul>
</li>
  <li><a href="#formal-specification" id="toc-formal-specification" class="nav-link" data-scroll-target="#formal-specification">Formal specification</a></li>
  <li>
<a href="#fitting-linear-regression-in-r" id="toc-fitting-linear-regression-in-r" class="nav-link" data-scroll-target="#fitting-linear-regression-in-r">Fitting linear regression in R</a>
  <ul class="collapse">
<li><a href="#r-syntax" id="toc-r-syntax" class="nav-link" data-scroll-target="#r-syntax">R syntax</a></li>
  <li><a href="#running-a-simple-linear-regression" id="toc-running-a-simple-linear-regression" class="nav-link" data-scroll-target="#running-a-simple-linear-regression">Running a simple linear regression</a></li>
  <li><a href="#interpreting-results" id="toc-interpreting-results" class="nav-link" data-scroll-target="#interpreting-results">Interpreting results</a></li>
  </ul>
</li>
  <li>
<a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model evaluation</a>
  <ul class="collapse">
<li><a href="#model-summary" id="toc-model-summary" class="nav-link" data-scroll-target="#model-summary">Model summary</a></li>
  <li><a href="#further-checks" id="toc-further-checks" class="nav-link" data-scroll-target="#further-checks">Further checks</a></li>
  </ul>
</li>
  <li><a href="#lab-activities" id="toc-lab-activities" class="nav-link" data-scroll-target="#lab-activities">Lab activities</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/UGQuants/quants_workbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header><section id="simple-linear-regression" class="level1"><h1>Simple Linear Regression</h1>
<section id="welcome" class="level2"><h2 class="anchored" data-anchor-id="welcome">Welcome</h2>
<p>In the previous lab we learned about correlation. We visualised the relationship of different types of variables. We also computed one correlation measure for two numeric variables, <em>Pearson’s</em> correlation. We used Pearson’s correlation to summarise the strength and direction of a linear association between two numeric variables. However, it presents some limitations. It can only be used for numeric variables, it allows only one pair of variables at a time, and it is only appropriate to describe a linear relationship.</p>
<p>Linear regression can overcome some of these limitations and it can be extended to achieve further purposes, such as using multiple variables or to make predictions for new scenarios. This technique is in fact common and one of the most popular in quantitative research in social sciences. Therefore, getting familiar with it will be important for you not only to perform your own analyses, but also to interpret and critically read the academic literature.</p>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Linear regression is appropriate only when the <strong>dependent</strong> variable is <strong>numeric</strong> (interval/ratio).</p>
<p>However, <strong>independent</strong> variables can be <strong>categorical</strong>, <strong>ordinal</strong>, or <strong>numeric</strong>. You can include <strong>more than one</strong> independent variable to evaluate how these relate to the dependent variable. In this lab we will start using only one explanatory variable. This is known as simple linear regression.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled" title="Don't Panic">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Don’t Panic
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will be covering linear regression over three weeks. Do not worry if everything this week doesn’t immediately make sense. We will revisit and build upon key ideas over labs 9 and 10 as well.</p>
<p>Please also do let me (Alasdair) know where anything is unclear or is confusing. We have been updating the lab content this year based on student feedback from previous years and value any feedback on the newest version so we can continue to make improvements.</p>
<p>As they cover some key concepts relevant for the summative assignment, I will aim to make further updates this year to Labs 8 - 10 based on any initial feedback.</p>
</div>
</div>
</section><section id="setup" class="level2"><h2 class="anchored" data-anchor-id="setup">Setup</h2>
<section id="r-markdown" class="level3"><h3 class="anchored" data-anchor-id="r-markdown">R Markdown</h3>
<p>For this lab, we will continue using the 2012 NILT survey to introduce linear models.</p>
<p>As usual, we will need to setup an R Markdown file for today’s lab. Remember if you are unsure about any of the steps below you can take a look back at <a href="./06-Lab6.html">Lab 6</a> which has more detailed explanation of each of the steps.</p>
<p>To set up a new R Markdown file for this lab, please use the following steps:</p>
<ol type="1">
<li>Please go to your ‘Lab Group ##’ in <a href="https://posit.cloud/">Posit Cloud</a> (log in if necessary);</li>
<li>Open your own copy of the ‘NILT’ project from the ‘Lab Group ##’;</li>
<li>Within the Files tab (bottom-right pane) click ‘New File’, then ‘R Markdown’ from the drop-down list of options;</li>
<li>Within the ‘Create a New File in Current Directory’ dialogue, name it ‘Lab-8-Simple-Linear-Regression.Rmd’ and click OK.</li>
<li>Feel free to make any adjustments to the YAML header.</li>
<li>Create a new code chunk, with <code>```{r setup, include=FALSE}</code> and in the chunk:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">knitr</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">opts_chunk</a></span><span class="op">$</span><span class="fu">set</span><span class="op">(</span>message <span class="op">=</span> <span class="cn">FALSE</span>, warning <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="7" type="1">
<li>Create another code chunk, named <code>preamble</code> and again with <code>include=FALSE</code>. Then add the following in the chunk:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load the packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Read NILT</span></span>
<span><span class="va">nilt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span><span class="op">(</span><span class="st">"data/nilt_r_object.rds"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Please note, we are loading the <code>haven</code> package again this week as we will be coercing more variables.</p>
<ol start="8" type="1">
<li>Run the <code>preamble</code> code chunk and if no errors, then everything is setup for this session.</li>
</ol></section><section id="dataframe-setup" class="level3"><h3 class="anchored" data-anchor-id="dataframe-setup">Dataframe Setup</h3>
<p>Let’s revisit the example from last week of the relationship between a respondent’s age and their spouse or partner’s age.</p>
<p>Firstly, let’s coerce the variables for the age of the respondent’s spouse/partner:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Age of Respondent's Spouse / Partner</span></span>
<span><span class="va">nilt</span><span class="op">$</span><span class="va">spage</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">nilt</span><span class="op">$</span><span class="va">spage</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Bonus Activity: We are coercing a variable again each week as a reminder for how to do it. However, we could remove the need to coerce variables we are re-using across each R Markdown file. In <a href="./03-Lab3.html">Lab 3</a> we created the <code>01_prep_nilt_2012.R</code> script in a sub-folder named <code>R</code>. Reviewing it, can you see where you could add a line of code to coerce <code>spage</code>? If so, modify your script, rerun it in full, then re-run the preamble code chunk in your R Markdown file for this week. After doing that, you’ll know you have successfully modified the script if you can run <code>class(nilt$spage)</code> in the Console and receive <code>"numeric"</code> as the output.</p>
<p>OK, we are going to use scatterplots to help visualise concepts related to linear regression. However, the NILT has hundreds of respondents, making very noisy plots. So, next let’s create a minimal sample of the dataset to only include 40 random observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># set a seed for randomisation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Filter where partner's age is not NA and take a random sample of 40</span></span>
<span><span class="va">nilt_sample</span> <span class="op">&lt;-</span> <span class="va">nilt</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">spage</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Select only respondent's age and spouse/partner's age</span></span>
<span><span class="va">nilt_sample</span> <span class="op">&lt;-</span> <span class="va">nilt_sample</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">rage</span>, <span class="va">spage</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-simple callout-caution">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Please note</strong>, we are creating a <code>nilt_sample</code> dataframe with a random selection of 40 observations - i.e.&nbsp;respondents - from the <code>nilt</code> data solely to help make it easier to visualise in the examples below.</p>
</div>
</div>
</div>
<p>To break down some of the code here:</p>
<ul>
<li>The <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> function lets us set a seed to fix the random number generator. Results remain random, but using the same seed means when running code in the <strong>same order</strong> makes the results reproducible.</li>
<li>We then <code>filter(!is.na(spage))</code>. <code>!</code> is the “NOT” operator, and <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> checks whether a value is NA (i.e.&nbsp;missing data). So, combined it is equivalent to saying “filter to remove all observations where the value for <code>spage</code> is NA”.</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n()</a></code> is then used to randomly select 40 of the observations that remain.</li>
</ul></section></section><section id="viewing-trends" class="level2"><h2 class="anchored" data-anchor-id="viewing-trends">Viewing Trends</h2>
<section id="scatter-plots" class="level3"><h3 class="anchored" data-anchor-id="scatter-plots">Scatter Plots</h3>
<p>Before we introduce linear regression itself, let’s start by visualising the relationship between the ages of the respondent and their spouse/partner.</p>
<p>We can do this with a scatter plot using the respondent’s spouse/partner age <code>spage</code> on the Y axis, and the respondent’s <code>rage</code> on the X axis. In ggplot, we compose the three key ggplot components - <code>ggplot(aes())</code>, <code>geom_...()</code>, and <code><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs()</a></code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nilt_sample</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">rage</span>, y <span class="op">=</span> <span class="va">spage</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Respondent's age vs respondent’s spouse/partner age"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Random Sample of 40 Observations"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Respondent's age"</span>, y <span class="op">=</span> <span class="st">"Respondent’s spouse/partner age"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="08-Lab8_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, even with this minimal example using 40 observations, there is a clear trend. If we were to guess - for the moment - it looks like the age of the spouse/partner might be generally the same as the respondent.</p>
<p>From the plot, it seems intuitive to draw a line that describes this general trend. Imagine a friend will draw this line for you. You will have to tell them some basic references on how to do it. You can, for example, specify a start point and an end point in the plot. Alternatively, which is what we will do below, you can specify a start point and a value that describes the slope of the line.</p>
<p>Thankfully, our friend is <code>ggplot</code>. We can pass it the two values we need - the start point and slope - in the <code><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline()</a></code> function. This will then draw a line that describes these points.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nilt_sample</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">rage</span>, y <span class="op">=</span> <span class="va">spage</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="co"># Draw line assuming exact same age of respondent and their partner/spouse</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>slope <span class="op">=</span> <span class="fl">1</span>, intercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Respondent's age vs respondent’s spouse/partner age"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Reference line assuming equal ages"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Respondent's age"</span>, y <span class="op">=</span> <span class="st">"Respondent’s spouse/partner age"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="08-Lab8_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>As noted in the comment in the code above, we are drawing this line at the moment as a ‘guesstimate’ a by-eye guess - that assumes the age of the spouse/partner is exactly the same as the respondent’s.</p>
</div>
</div>
</div>
<p>To draw a line like this, we used 0 as the starting value in the <code><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline()</a></code> function. In statistics, this is known as the <em>intercept</em> and it is often represented with a Greek letter and a zero sub-index as <span class="math inline">\(\beta_0\)</span> (beta-naught) or with <span class="math inline">\(\alpha\)</span> (alpha). The location of the intercept can be found along the vertical axis (in this case it is not visible due to ages of respondents and their spouses/partners being 20+).</p>
<p>The second value we passed to describe the line is the <em>slope</em>, which uses the X axis as the reference. The slope value is multiplied by the value of the X axis. Therefore, a slope of 0 is completely horizontal. In this example, a slope of 1 produces a line at 45º. The slope is often represented with the Greek letter beta and a sequential numeric sub-index like this: <span class="math inline">\(\beta_1\)</span> (b.</p>
</section><section id="was-this-a-good-guess" class="level3"><h3 class="anchored" data-anchor-id="was-this-a-good-guess">Was this a good guess?</h3>
<p>Having drawn a line assuming respondents and their spouses/partners have the same age, how does that compare to our actual data?</p>
<p>First, let’s create a variable in our dataframe that matches our guess. We can do this by taking the starting point - the ‘intercept’ - and adding the steepness factor - the ‘slope’. We will store the results in a column called <code>line1</code>. After that, we can print the ‘head’ of our dataframe using the <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function to see the first few rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># create values for the guess line 1</span></span>
<span><span class="va">nilt_sample</span> <span class="op">&lt;-</span> <span class="va">nilt_sample</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>line1 <span class="op">=</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">rage</span> <span class="op">*</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co"># print results</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">nilt_sample</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
   rage spage line1
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    40    39    40
2    54    51    54
3    66    59    66
4    60    71    60
5    35    34    35
6    67    57    67</code></pre>
</div>
</div>
<p>From the above, we can see that the respondent’s age <code>rage</code> and the column that we just created <code>line1</code>, are identical… which is not a surprise when our guess for now is that a respondent and their spouse/partner will be the same age.</p>
<p>But to return to our question, is the line we just drew good enough to represent the general trend in the relationship between the age of a respondent and their spouse/partner?</p>
<p>To answer this question, for each point of the plot we can measure the distance from it to where it would be on ‘line 1’ - which to repeat is a line drawn assuming participant’s and their spouse/partner are the same age.</p>
<p>We can use <code>ggplot</code> to draw this for us, using a dashed line to show the distance between each dot and our line 1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nilt_sample</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">rage</span>, y <span class="op">=</span> <span class="va">spage</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>slope <span class="op">=</span> <span class="fl">1</span>, intercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>xend <span class="op">=</span> <span class="va">rage</span>, yend <span class="op">=</span> <span class="va">line1</span><span class="op">)</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Respondent's age vs respondent’s spouse/partner age"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Distances from each point to the guess line (residuals)"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Respondent's age"</span>, y <span class="op">=</span> <span class="st">"Respondent’s spouse/partner age"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="08-Lab8_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice how this code is the same as our original scatterplot, we just added <code><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment()</a></code>. For each dot, this function draws a line between it and the end points we give. By passing it <code>xend = rage</code> we are effectively telling it not to draw any horizontal line, and <code>yend = line1</code> tells it to draw a line from the dot to where it would be if the spouse/partner’s age was the same as the respondents. We can then specify to used dashed lines with <code>linetype = "dashed"</code>.</p>
</section><section id="residuals" class="level3"><h3 class="anchored" data-anchor-id="residuals">Residuals</h3>
<p>This distance between the observation and the line is known as the residual or the error and it is often expressed with the Greek letter <span class="math inline">\(\epsilon\)</span> (epsilon). Numerically, we can calculate this by computing the difference between the known value (the observed) and the <strong>guessed</strong> value.</p>
<p>Formally, the guessed number is called the expected value (also known as predicted/estimated value). Normally, the expected values in statistics are represented by putting a hat like this <span class="math inline">\(\hat{}\)</span> on the letters.</p>
<p>Since the independent variable is usually located on the X axis and the dependent variable on the Y axis. We write write the expected (predicated) value with a hat on the Y like this: <span class="math inline">\(\hat{y}\)</span> (y-hat).</p>
<p>Let’s estimate the residuals for each of the observations by subtracting <span class="math inline">\(\hat{y}_i\)</span> from <span class="math inline">\(y_i\)</span> (<code>spage</code> - <code>line1</code>) and store it in a column called <code>residuals</code>. Again we can use the <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function to see the first few lines of our dataframe.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># estimate residuals</span></span>
<span><span class="va">nilt_sample</span> <span class="op">&lt;-</span> <span class="va">nilt_sample</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>residuals <span class="op">=</span> <span class="va">spage</span> <span class="op">-</span> <span class="va">line1</span><span class="op">)</span></span>
<span><span class="co"># print first 6 values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">nilt_sample</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
   rage spage line1 residuals
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1    40    39    40        -1
2    54    51    54        -3
3    66    59    66        -7
4    60    71    60        11
5    35    34    35        -1
6    67    57    67       -10</code></pre>
</div>
</div>
<p>Coming back once again to the question, is my line good enough?</p>
<p>We could sum all these residuals as an overall measure to know how good our line is. From the previous plot, we see that some of the expected ages are higher than the actual values, whilst others are below. This produces negative and positive residuals. If we simply sum them, they would compensate each other and this would not tell us much about the overall magnitude of the difference.</p>
<p>To overcome this problem, we square each residual - multiply the residual by itself. This will make all of our values positive - “-3 x -3 = 9” - making it possible to sum them all together.</p>
</section></section><section id="key-this-and-expand---could-work-as-initial-return-to-example-from-last-week" class="level2"><h2 class="anchored" data-anchor-id="key-this-and-expand---could-work-as-initial-return-to-example-from-last-week">KEY THIS AND EXPAND - could work as initial return to example from last week</h2>
<p>This is known as the <em>sum of squared residuals</em> (SSR) and we can use this as the criterion to measure how good our line is with respect to the overall trend of the points.</p>
<p>For line 1, we can easily calculate the SSR as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># '^' is used for power - so `^2` squares our values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">nilt_sample</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1325</code></pre>
</div>
</div>
<p>The sum of squared residuals for line 1 is 1,325.</p>
<section id="using-a-linear-model" class="level3"><h3 class="anchored" data-anchor-id="using-a-linear-model">Using a Linear Model</h3>
<p>How does our line though compare to other potential lines we could have drawn to describe the trend? We can try different lines to find the combination of intercept and slope that produces the smallest error (SSR). How can we find the best line to describe the trend?</p>
<p>To our luck, we can find the best values using a well established technique called <em>Ordinary Least Squares</em> (OLS). Ordinary Least Squares chooses the line that minimises the Sum of Squared Residuals (SSR). We do not need to know the details for now. The important thing is that this procedure guarantees to find a line that produces the smallest possible error (SSR).</p>
<p>In <code>R</code>, it is very simple to fit a linear model and we do not need to go through each of the steps above <strong>manually</strong> nor to memorise all the steps.</p>
<p>To fit a linear model, simply use the function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and save the result in an object called <code>m1</code> (for ‘model 1’) and print it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">spage</span> <span class="op">~</span> <span class="va">rage</span>, data <span class="op">=</span> <span class="va">nilt_sample</span><span class="op">)</span></span>
<span><span class="va">m1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = spage ~ rage, data = nilt_sample)

Coefficients:
(Intercept)         rage  
      6.299        0.875  </code></pre>
</div>
</div>
<p>For simple linear regression, the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function takes arguments in form of <code>lm(dependent-variable ~ independent-variable, dataframe)</code>, with the <code>~</code> (tilde) operator is used to separate the dependent variable and independent variable.</p>
<p>So, this is the optimal intercept <span class="math inline">\(\beta_0\)</span> and slope <span class="math inline">\(\beta_1\)</span> that minimises the Sum of Squared Residuals (SSR).</p>
<p>Let’s see what the SSR is compared to our original arbitrary guess:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1175.209</code></pre>
</div>
</div>
<p>Yes, this is better than before. Our line that assumed respondents and their spouse/partner had the same age had an SSR value of 1,325. So, this linear model is better as the SSR value is smaller.</p>
<p>To help visualise it, let’s plot the line we guessed and the optimal line together:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">nilt_sample</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">rage</span>, y <span class="op">=</span> <span class="va">spage</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>slope <span class="op">=</span> <span class="fl">1</span>, intercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Respondent's age vs respondent’s spouse/partner age"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Comparing a guess line (red) with the OLS best-fit line (blue)"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Respondent's age"</span>, y <span class="op">=</span> <span class="st">"Respondent’s spouse/partner age"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="08-Lab8_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Again, notice how this is just the same code we used to draw our original guess, with an added line using <code><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth()</a></code> to draw a line using the linear model. We pass it two arguments, <code>method = "lm"</code>, to specify that a linear model should be used to draw the line, and <code>se = FALSE</code> so it draws only the line. (By default, <code><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth()</a></code> has <code>se = TRUE</code> to include confidence bands so we need to explicitly use <code>se = FALSE</code> to turn them off.)</p>
<p>The blue is the optimal solution based on a linear model, whereas the red was just our initial arbitrary guess. We can see that the optimal is more balanced than the red in relation to the observed data points.</p>
</section></section><section id="formal-specification" class="level2"><h2 class="anchored" data-anchor-id="formal-specification">Formal specification</h2>
<p>Now you are ready for the formal specification of the linear model.</p>
<p>After the introduction above, it is easy to take the pieces apart. In essence, the simple linear model is telling us that the dependent value <span class="math inline">\(y\)</span> is defined by a line that intersects the vertical axis at <span class="math inline">\(\beta_0\)</span>, plus the multiplication of the slope <span class="math inline">\(\beta_1\)</span> by the value of <span class="math inline">\(x_1\)</span>, plus some residual <span class="math inline">\(\epsilon\)</span>. The second part of the equation is just telling us that the residuals are normally distributed (that is when a histogram of the residuals follows a bell-shaped curve).</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \varepsilon_i, \qquad \varepsilon_i \sim \mathcal{N}(0, \sigma^2)
\]</span></p>
<p>You do not need to memorize this equation, but being familiar to this type of notation will help you to expand your skills in quantitative research.</p>
</section><section id="fitting-linear-regression-in-r" class="level2"><h2 class="anchored" data-anchor-id="fitting-linear-regression-in-r">Fitting linear regression in R</h2>
<section id="r-syntax" class="level3"><h3 class="anchored" data-anchor-id="r-syntax">R syntax</h3>
<p>We already fitted our first linear model using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> above, which of course stands for <em>linear model</em>, but let’s go back through it in relation to the specifications.</p>
<p>The first argument takes the dependent variable, then, we use tilde <code>~</code> to express that this is <em>followed by</em> the independent variable. Then, we specify the data set separated by a comma, as shown below:</p>
<div class="cell">
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>Example Code - do not run</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">dependent_variable</span> <span class="op">~</span> <span class="va">independent_variable</span>, <span class="va">data</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section><section id="running-a-simple-linear-regression" class="level3"><h3 class="anchored" data-anchor-id="running-a-simple-linear-regression">Running a simple linear regression</h3>
<p>Now, let’s try with the full nilt data set.</p>
<p>First, we will fit a linear model using the same variables as the example above but including all the observations - remember that before we were working only with a small random sample of 40 observations.</p>
<p>The first argument is the respondent’s spouse/partner age <code>spage</code>, followed by the respondent’s age <code>rage</code>. Let’s assign the model to an object called <code>m2</code> (for ‘model 2’) and print it after.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">spage</span> <span class="op">~</span> <span class="va">rage</span>, data <span class="op">=</span> <span class="va">nilt</span><span class="op">)</span></span>
<span><span class="va">m2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = spage ~ rage, data = nilt)

Coefficients:
(Intercept)         rage  
     3.7039       0.9287  </code></pre>
</div>
</div>
<p>The output first displays the formula employed to estimate the model - under <code>Call:</code>. Then, it shows us the estimated values for the intercept and the slope for the age of the respondent, these estimated values are called coefficients.</p>
<p>In this model, the coefficients differ from the ones in the example above (m1). This is because as we are now using the full <code>nilt</code> dataframe we have more information to fit the line. Despite the difference, we see that the relationship is still in the same direction (positive). In fact, the value of the slope <span class="math inline">\(\beta_1\)</span> did not change much if you look at it carefully (0.87 vs 0.92).</p>
</section><section id="interpreting-results" class="level3"><h3 class="anchored" data-anchor-id="interpreting-results">Interpreting results</h3>
<p>But what are the slope and intercept telling us? The first thing to note is that the slope is positive, which means that the relationship between the respondent age and their spouse/partner age are in the same direction. When the age of the respondent goes up, the age of their spouse/partner is expected to go up as well.</p>
<p>In our model, the intercept does not have a meaningful interpretation on its own. What we mean by saying it is not meaningful is that it would not be logical to say that when the respondent’s age is 0 their partner would be expected to be 3.70 years old. Instead, the interpretations should be made only within the range of the values used to fit the model (the youngest age in this data set is 18).</p>
<p>The slope can be interpreted as follows: For every year older the respondent is, the partner’s age is expected to change by 0.92. In other words, the respondents are expected to have a partner who is 0.92 times years older than themselves. Or, to put it in more simple terms, for each 1-year increase in the respondent’s age, the expected spouse/partner age increases by 0.92 years. On average then, partners are slightly younger than respondents.</p>
<p>In this case, the units of the dependent variable are the same as the independent (age vs age) which make it easy to interpret. In reality, there might be more factors that potentially affect how people select their partners, such as gender, education, race/ethnicity, etc. For now, we are keeping things ‘simple’ by using only these two variables.</p>
<p>Let’s practice with another example. What if we are interested in income?</p>
<p>We can use annual personal income <code>persinc2</code> as the dependent variable and the number of hours worked a week <code>rhourswk</code> as the independent variable. We’ll assign the result to an object called <code>m3</code> (for ‘model 3’).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">persinc2</span> <span class="op">~</span> <span class="va">rhourswk</span>, data <span class="op">=</span> <span class="va">nilt</span><span class="op">)</span></span>
<span><span class="va">m3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = persinc2 ~ rhourswk, data = nilt)

Coefficients:
(Intercept)     rhourswk  
     5170.4        463.2  </code></pre>
</div>
</div>
<p>This time, the coefficients look quite different. The results are telling us that for every additional hour worked a week a respondent is expected to earn £463.2 more a year than other respondent.</p>
<p>Note that the input units are not the same in the interpretation. The dependent variable is in pounds earned a year and the independent is in hours worked a week. Does this mean that someone who works 0 hours a week is expected to earn £5170.4 a year (given the fitted model <span class="math inline">\(\hat{persinc2} =  5170.4 + 0*463.2\)</span>) or that someone who works 110 hours a week (impossible!) is expected to earn £56K a year? We should only make reasonable interpretations of the coefficients within the range analysed.</p>
<p>Finally, an important thing to know when interpreting linear models using cross-sectional data (data collected in a single time point only) is: <strong><em>correlation does not imply causation</em></strong>. Variables are often correlated with other non-observed variables which may cause the effects observed on the independent variable in reality. This is why we cannot always be sure that X is causing the observed changes on Y.</p>
</section></section><section id="model-evaluation" class="level2"><h2 class="anchored" data-anchor-id="model-evaluation">Model evaluation</h2>
<section id="model-summary" class="level3"><h3 class="anchored" data-anchor-id="model-summary">Model summary</h3>
<p>So far, we have talked about the basics of the linear model. If we print a summary of the model, using the handy <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function, we can obtain more information to evaluate it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = spage ~ rage, data = nilt)

Residuals:
    Min      1Q  Median      3Q     Max 
-33.211  -2.494   0.075   2.505  17.578 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.70389    0.66566   5.564    4e-08 ***
rage         0.92869    0.01283  72.386   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.898 on 589 degrees of freedom
  (613 observations deleted due to missingness)
Multiple R-squared:  0.8989,    Adjusted R-squared:  0.8988 
F-statistic:  5240 on 1 and 589 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The summary output has several parts. This can look intimidating at first, but we can break it down bit-by-bit. Let’s focus on:</p>
<ul>
<li>first the call</li>
<li>second the residuals</li>
<li>third the coefficients</li>
<li>fourth the goodness-of-fit measures</li>
</ul>
<p>These are highlighted in the screenshot below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/r_studio_lab6_model_summary.png" class="img-fluid figure-img"></p>
<figcaption>Model summary</figcaption></figure>
</div>
<p>The first part, <strong>Call</strong>, is simply printing the variables that were used to produce the models.</p>
<p>The second part, the <strong>Residuals</strong>, provides a small summary of the residuals by quartile, including minimum and maximum residual values. Remember the second part of the formal specification of the model? Well, this is where we can see in practice the distribution of the residuals. The quartiles show typical prediction errors. For example, half of the residuals lie between the 1st and 3rd quartiles. So by looking at the values for the first and third quartile, we can see that half of the predicted values by the model are <span class="math inline">\(\pm\)</span> 2.5 years old away from the observed partner’s age… not that bad.</p>
<p>The third part is about the <strong>coefficients</strong>. This time, the summary provides more information about the intercept and the slope than just the estimated coefficients as before. Usually, we focus on the independent variables in this section, <code>rage</code> in our case. The second column, standard error, tell us how large the error of the slope is, which is small for our variable. The third and fourth columns provide measures about the statistical significance of the relationship between the dependent and independent variable.</p>
<p>The most commonly reported is the p-value (the fourth column). R uses scientific notation for very small p-values. In our result the p-value is <code>&lt;2e-16</code>, which means a number less than 0.0000000000000002, <a href="https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php#:~:text=The%20proper%20format%20for%20scientific,equivalent%20to%20the%20original%20number.">you can learn about scientific notation here</a>).</p>
<p>As a general agreed principle, <strong>if the p-value is equal or less than 0.05 (<span class="math inline">\(p\)</span> ≤ 0.05), we can reject the null hypothesis, and say that the relationship between the dependent variable and the independent is significant.</strong> In our case, the p-value is far lower than 0.05. So, we can say that the relationship between the respondent’s spouse/partner age and the respondent’s age is significant. In fact, R includes codes for each coefficient to help us to identify the significance. In our result, we got three stars/asterisks. This is because the value is less than 0.001. R assigns two stars if the p-value is less than 0.01, and one star if it is lower than 0.05. (P‑values, however, are just one part of the story; always read them alongside effect size, confidence intervals, and substantive meaning.)</p>
<p>In the fourth area, we have various <strong>goodness-of-fit measures</strong>. Overall, these measures tell us how well the model represents our data. For now, let’s focus on the <em>adjusted R-squared</em>.</p>
<p>R-squared is the proportion of variation in the outcome explained by the model. It ranges from 0 to 1: 0 means none of the variance is explained; 1 means all variance in the sample is explained by the model. Adjusted R-squared penalises adding variables that do not improve the model. In the social sciences, modest R-squared values are common.</p>
<p>Adjusted R-squared then can be understood as the proportion (multiply it by 100 to report a percentage) of variance explained by the model, adjusted for the number of independent variables used. In our age-age example, the model explains 89.88% percent of the total variance. This is a good fit, but this is because we are modelling a quite “obvious” relationship. The R-squared describes the model file, it does not judge the quality of our analysis.</p>
<p>You may wonder why we do not report the sum of squared residuals (SSR), as we covered in our initial example. This is because the scale of the SSR is in the units used to fit the model, which would make it difficult to compare our model with other models that use different units or different variables. Conversely, the adjusted R-squared is expressed in relative terms which makes it a more suitable measure to compare with other models. An important thing to note is that the output is telling us that this model excluded 613 observations which were missing in our dataset. This is because we do not have the age of the respondent’s partner in 613 of the rows. Missing spouse/partner ages can occur for serveral reasons. For example, the respondent may not have a parter, or choose not to answer.</p>
<p>In academic papers in the social sciences, usually the measures reported are the coefficients, p-values, the adjusted R-squared, and the size of the sample used to fit the model (number of observations).</p>
</section><section id="further-checks" class="level3"><h3 class="anchored" data-anchor-id="further-checks">Further checks</h3>
<p>The linear model, as many other techniques in statistics, relies on assumptions. These refer to characteristics of the data that are taken for granted to generate the estimates. It is the task of the modeller/analyst to make sure the data used follows these assumptions. One simple yet important check is to examine the distribution of the residuals, which ought to follow a normal distribution.</p>
<p>Do the residuals follow a normal distribution in our model, <code>m2</code>? We can go further and plot a histogram to graphically evaluate it. Use the function <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> to extract the residuals from our object <code>m2</code>, and then plot a histogram with the base R function <code><a href="https://rdrr.io/r/graphics/hist.html">hist()</a></code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m2</span><span class="op">)</span>, breaks <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="08-Lab8_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Overall, it seems that the residuals follow the normal distribution reasonably well, with the exception of the negative value to the left of the plot. Very often when there is a strange distribution or different to the normal, it is because one of the assumptions is violated. If that is the case we cannot trust the coefficient estimates. In the next lab we will talk more about the assumptions of the linear model. For now, we will leave it here and get some practice.</p>
</section></section><section id="lab-activities" class="level2"><h2 class="anchored" data-anchor-id="lab-activities">Lab activities</h2>
<p>In your R Markdown file, use the <code>nilt</code> dataset to:</p>
<ol type="1">
<li>Plot a scatter plot using <code>ggplot</code>. In the aesthetics, locate <code>rhourswk</code> in the X axis, and <code>persinc2</code> in the Y axis. In the <code><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point()</a></code> jitter the points by specifying the <code>position = 'jitter'</code>. Also, include the best fit line using the <code><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth()</a></code> function, and specify the <code>method = 'lm'</code> inside.</li>
<li>Print the summary of <code>m3</code> using the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function.</li>
<li>Is the relationship of hours worked a week statistically significant?</li>
<li>What is the adjusted R-squared? How would you interpret it?</li>
<li>What is the sample size to fit the model?</li>
<li>What is the expected income in pounds a year for a respondent who works 30 hours a week according to coefficients of this model?</li>
<li>Plot a histogram of the residuals of <code>m3</code> using the <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> function inside <code><a href="https://rdrr.io/r/graphics/hist.html">hist()</a></code>. Do the residuals look normally distributed (as in a bell-shaped curve)?</li>
<li>Discuss your answers with your neighbour or tutor.</li>
</ol>


</section></section></main><!-- /main --><script>
(function () {
  function installShim() {
    const H = window.Headroom;
    if (!H || H._patched) return !!H && H._patched;

    const Original = H;
    function Patched(el, opts) {
      const desired = { offset: 180, tolerance: { up: 40, down: 10 } };
      const merged = Object.assign({}, opts, desired);
      const inst = new Original(el, merged);
      try { el._headroom = inst; } catch (_) {}
      return inst;
    }
    Object.assign(Patched, Original);
    Patched.prototype = Original.prototype;
    Patched._patched = true;
    window.Headroom = Patched;
    return true;
  }

  if (!installShim()) {
    const t = setInterval(() => { if (installShim()) clearInterval(t); }, 10);
    window.addEventListener("DOMContentLoaded", () => clearInterval(t), { once: true });
  }
})();
</script><script>
(function () {
  function headerEl() { return document.querySelector("#quarto-header"); }
  function headroomInst() { const h = headerEl(); return h && h._headroom ? h._headroom : null; }
  function setScrollPaddingTop(px) { document.documentElement.style.setProperty("scroll-padding-top", px); }
  function visibleNavbarHeight() { const h = headerEl(); return h ? `${h.offsetHeight}px` : "0px"; }

  function ensureFab() {
    let fab = document.querySelector(".q-nav-fab");
    if (!fab) {
      fab = document.createElement("button");
      fab.className = "q-nav-fab";
      fab.type = "button";
      fab.setAttribute("aria-label", "Show navbar (Alt+Shift+H)");
      fab.setAttribute("title", "Show navbar (Alt+Shift+H)");
      fab.innerHTML = '<span aria-hidden="true">≡</span>';
      fab.addEventListener("click", () => toggleNav(false));
      document.body.appendChild(fab);
    }
    return fab;
  }

  function toggleNav(forceHidden) {
    const body = document.body;
    const wantHide = (forceHidden === undefined) ? !body.classList.contains("nav-hidden") : forceHidden;
    const hr = headroomInst();

    if (wantHide) {
      body.classList.add("nav-hidden");
      if (hr && typeof hr.freeze === "function") hr.freeze();
      body.dataset.prevScrollPaddingTop = getComputedStyle(document.documentElement).scrollPaddingTop;
      setScrollPaddingTop("0px");
      ensureFab().style.display = "inline-flex";
    } else {
      body.classList.remove("nav-hidden");
      if (hr && typeof hr.unfreeze === "function") hr.unfreeze();
      const prev = body.dataset.prevScrollPaddingTop || visibleNavbarHeight();
      setScrollPaddingTop(prev);
      const fab = document.querySelector(".q-nav-fab");
      if (fab) fab.style.display = "none";
    }
  }

  function bindHotkey() {
    document.addEventListener("keydown", (e) => {
      const inEditable = e.target.closest("input, textarea, [contenteditable='true']");
      if (inEditable) return;
      if (e.altKey && e.shiftKey && e.key.toLowerCase() === "h") {
        e.preventDefault();
        toggleNav();
      }
    });
  }

  function bindNavbarToolIfPresent() {
    const tool = document.querySelector('#quarto-header [aria-label*="Toggle navbar"]');
    if (!tool) return;

    // keep the toggle working
    tool.setAttribute("href", "#");
    tool.addEventListener("click", (e) => { e.preventDefault(); toggleNav(); });

    // ONE native tooltip: on the icon only
    const label = tool.getAttribute("aria-label") || "Toggle navbar";
    tool.removeAttribute("title");                // no tooltip on the anchor
    const icon = tool.querySelector("i, svg");    // Bootstrap Icons render as <i> or <svg>
    if (icon) icon.setAttribute("title", label);

    tool.setAttribute("role", "button");
  }

  function start() { bindHotkey(); bindNavbarToolIfPresent(); }

  (document.readyState === "loading")
    ? document.addEventListener("DOMContentLoaded", start)
    : start();
})();
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ugquants\.github\.io\/quants_workbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./07-Lab7.html" class="pagination-link" aria-label="**Lab 7** Correlation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><strong>Lab 7</strong> Correlation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-Lab9.html" class="pagination-link" aria-label="**Lab 9** Multiple Linear Regression (part 1)">
        <span class="nav-page-text"><strong>Lab 9</strong> Multiple Linear Regression (part 1)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/UGQuants/quants_workbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Licensed under <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <i class="fa-brands fa-creative-commons-sa" aria-label="creative-commons-sa"></i> <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0</a></p>
</div>
  </div>
</footer>


</body></html>