project:
  type: website
  output-dir: docs

execute:
  freeze: auto

callout-appearance: simple

website:
  title: "Lab Workbook"
  announcement:
    icon: info-circle
    dismissible: true
    content: "**Reminder** - a link to join your RStudio Cloud group is available in the lab group forums on Moodle"
    type: info
    position: below-navbar
  page-navigation: true
  bread-crumbs: false
  reader-mode: true
  site-url: https://ugquants.github.io/quants_workbook/
  repo-url: https://github.com/UGQuants/quants_workbook
  issue-url: https://github.com/UGQuants/quants_workbook/issues/new
  search:
    location: navbar
    type: overlay
  navbar:
    pinned: false
    logo: "brand/uofg-keyline.png"
    background: "#011451"
    tools:
      - icon: github
        href: https://github.com/UGQuants/quants_workbook
        text: Workbook GitHub
    right:
      - text: "Help!"
      - text: "Reference"
      - text: "Additional"
      - text: "Assessments"

  sidebar:
    style: "floating"
    align: left
    border: false
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "**Lab 1** Introduction to R"
        href: 01-intro.qmd
      - text: "**Lab 2** Data in R"
        href: 02-Lab2.qmd
      - text: "**Lab 3** Data Wrangling"
        href: 03-Lab3.qmd
      - text: "**Lab 4** Exploratory Data Analysis"
        href: 04-Lab4.qmd
      - text: "**Lab 5** Reporting in R Markdown"
        href: 05-Lab5.qmd
      - text: "**Lab 6** Visual Exploratory Analysis"
        href: 06-Lab6.qmd
      - text: "**Lab 7** Correlation"
        href: 07-Lab7.qmd
      - text: "**Lab 8** Simple Linear Regression"
        href: 08-Lab8.qmd
      - text: "**Lab 9** Multivariate Linear Regression"
        href: 09-Lab9.qmd
      - text: "**Lab 11** Interpretive Report Assessment"
        href: 11-Lab11.qmd
      - 11-Answers.qmd
      - 12-InterpretiveReportStructure.qmd
      - 13-RFAQ.qmd
      - references.qmd

  page-footer:
    left: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org)"
    right: "Licensed under {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}} [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

bibliography:
  - book.bib
  - packages.bib

format:
  html:
    respect-user-color-scheme: true
    toc: true
    toc-expand: true
    code-link: true
    code-overflow: wrap
    link-citations: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    css:
      - style.css
