---
title: "Assessments"
---

Remember to also check the [Assessment section on Moodle](https://moodle.gla.ac.uk/course/section.php?id=746339), which contains further information and the Turnitin submission areas.

::: {.callout-important title="Deadlines"}
- [Formative Assessment](formative.qmd) – 12 noon, Friday 31st October 2025
- [Summative Assessments](summative.qmd) ([Reflective Summary](summative.qmd#reflective-course-summary) + [Interpreting Quantitative Findings Report](summative.qmd#interpreting-quantitative-findings-report)) - 12 noon, Monday 15th December 2025.
:::

### Setting Up RStudio Projects for the Assessments

We provide template projects to use for the formative and summative assessments via GitHub repositories. This is similar to how we shared the template project we used for Labs 1 and 2.

Please see the [Setup Assessment Projects](creating-assessment-projects.qmd) page for step-by-step guide and links to use.

### GenAI and the Assessments

The University of Glasgow's [position on GenAI use](https://www.gla.ac.uk/myglasgow/sld/ai/) is not to prohibit GenAI use, but instead to support you to use it "effectively, ethically, critically, and transparently".

For the assessments on this course, you are allowed to use GenAI tools in some specific ways as part of your assessment.

The use of GenAI tools can augment specific parts of your submission; such as to help with drafting and editing, and to explore key ideas.

However, key to the interpretive report assessment is using R and interpreting research findings. It is, therefore, not permitted to use GenAI to write R code for your analysis nor to interpret the statistical results. It is acceptable to use GenAI to receive textbook code examples and explanations, but not the exact code needed for the analysis. Similarly, it is acceptable to use GenAI for explanations on how to interpret statistics in general, but not the exact stats from your analysis.

If using any form of GenAI tool, you must acknowledge how the tools have been used within your work. You cannot submit any content produced by GenAI as your own work.

[RStudio Helper](../help/rstudio_helper.qmd) is an example ChatGPT Custom GPT / Copilot Saved Prompt created for use on this module. It has instructions that guide it towards providing more useful responses that aid learning and that align with the specific ways GenAI can be used for the assessments. However, whilst it has these instructions, GenAI does not always reliably and consistently follow them. So, still exercise the same caution with its responses and use prompts that align with permitted use cases for the assessments.
