<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lab 8 Linear model: Simple linear regression | UG Quantitative Methods in the Social Sciences lab workbook</title>
  <meta name="description" content="This is the workbook you will use for the Quantitative Methods in the Social Sciences lab sessions." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Lab 8 Linear model: Simple linear regression | UG Quantitative Methods in the Social Sciences lab workbook" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the workbook you will use for the Quantitative Methods in the Social Sciences lab sessions." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lab 8 Linear model: Simple linear regression | UG Quantitative Methods in the Social Sciences lab workbook" />
  
  <meta name="twitter:description" content="This is the workbook you will use for the Quantitative Methods in the Social Sciences lab sessions." />
  

<meta name="author" content="by J Rafael Verudzco Torres and Mark Wong" />


<meta name="date" content="2024-11-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlation.html"/>
<link rel="next" href="multi-lm.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">UG Quantitative Methods in the Social Sciences: Workbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="lab-intro.html"><a href="lab-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lab-intro.html"><a href="lab-intro.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lab-intro.html"><a href="lab-intro.html#r-a-flexible-tool"><i class="fa fa-check"></i><b>1.1.1</b> R: a flexible tool</a></li>
<li class="chapter" data-level="1.1.2" data-path="lab-intro.html"><a href="lab-intro.html#advantages-of-using-r"><i class="fa fa-check"></i><b>1.1.2</b> Advantages of using R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="lab-intro.html"><a href="lab-intro.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="lab-intro.html"><a href="lab-intro.html#setting-up-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Setting up RStudio</a></li>
<li class="chapter" data-level="1.2.2" data-path="lab-intro.html"><a href="lab-intro.html#rstudio-environment"><i class="fa fa-check"></i><b>1.2.2</b> RStudio environment</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="lab-intro.html"><a href="lab-intro.html#hands-on-r"><i class="fa fa-check"></i><b>1.3</b> Hands on R</a></li>
<li class="chapter" data-level="1.4" data-path="lab-intro.html"><a href="lab-intro.html#activity"><i class="fa fa-check"></i><b>1.4</b> Activity</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lab2.html"><a href="lab2.html"><i class="fa fa-check"></i><b>2</b> Data in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lab2.html"><a href="lab2.html#welcome-back"><i class="fa fa-check"></i><b>2.1</b> Welcome back!</a></li>
<li class="chapter" data-level="2.2" data-path="lab2.html"><a href="lab2.html#learn-packages"><i class="fa fa-check"></i><b>2.2</b> R Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="lab2.html"><a href="lab2.html#installing-packages"><i class="fa fa-check"></i><b>2.2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2.2" data-path="lab2.html"><a href="lab2.html#activity-1"><i class="fa fa-check"></i><b>2.2.2</b> Activity:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="lab2.html"><a href="lab2.html#types-of-variables"><i class="fa fa-check"></i><b>2.3</b> Types of variables</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="lab2.html"><a href="lab2.html#activity-2"><i class="fa fa-check"></i><b>2.3.1</b> Activity:</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="lab2.html"><a href="lab2.html#more-operators-and-some-essential-symbols"><i class="fa fa-check"></i><b>2.4</b> More operators and some essential symbols</a></li>
<li class="chapter" data-level="2.5" data-path="lab2.html"><a href="lab2.html#black-lives-matter"><i class="fa fa-check"></i><b>2.5</b> Black lives matter!</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="lab2.html"><a href="lab2.html#downloading-and-reading-the-data"><i class="fa fa-check"></i><b>2.5.1</b> Downloading and reading the data</a></li>
<li class="chapter" data-level="2.5.2" data-path="lab2.html"><a href="lab2.html#examining-the-data"><i class="fa fa-check"></i><b>2.5.2</b> Examining the data</a></li>
<li class="chapter" data-level="2.5.3" data-path="lab2.html"><a href="lab2.html#data-wrangling"><i class="fa fa-check"></i><b>2.5.3</b> Data wrangling</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="lab2.html"><a href="lab2.html#activities"><i class="fa fa-check"></i><b>2.6</b> Activities</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html"><i class="fa fa-check"></i><b>3</b> Data wrangling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#importing-and-data-wrangling"><i class="fa fa-check"></i><b>3.1</b> Importing and data wrangling</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#downloading-and-reading-the-data-1"><i class="fa fa-check"></i><b>3.1.1</b> Downloading and reading the data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#data-wrangling-2"><i class="fa fa-check"></i><b>3.2</b> Data wrangling</a></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#read-the-clean-dataset"><i class="fa fa-check"></i><b>3.3</b> Read the clean dataset</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-3"><i class="fa fa-check"></i><b>3.3.1</b> Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#getting-started-1"><i class="fa fa-check"></i><b>4.1</b> Getting started</a></li>
<li class="chapter" data-level="4.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exploratory-analysis"><i class="fa fa-check"></i><b>4.2</b> Exploratory analysis</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-overview"><i class="fa fa-check"></i><b>4.2.1</b> Data overview</a></li>
<li class="chapter" data-level="4.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#categorical-data"><i class="fa fa-check"></i><b>4.2.2</b> Categorical data</a></li>
<li class="chapter" data-level="4.2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#activity-1-1"><i class="fa fa-check"></i><b>4.2.3</b> Activity 1</a></li>
<li class="chapter" data-level="4.2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#continuous-numeric-data"><i class="fa fa-check"></i><b>4.2.4</b> Continuous (numeric) data</a></li>
<li class="chapter" data-level="4.2.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#putting-it-all-together"><i class="fa fa-check"></i><b>4.2.5</b> Putting it all together</a></li>
<li class="chapter" data-level="4.2.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#activity-2-1"><i class="fa fa-check"></i><b>4.2.6</b> Activity 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="reporting-in-r-markdown.html"><a href="reporting-in-r-markdown.html"><i class="fa fa-check"></i><b>5</b> Reporting in R Markdown</a>
<ul>
<li class="chapter" data-level="5.1" data-path="reporting-in-r-markdown.html"><a href="reporting-in-r-markdown.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="reporting-in-r-markdown.html"><a href="reporting-in-r-markdown.html#r-markdown"><i class="fa fa-check"></i><b>5.2</b> R Markdown</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="reporting-in-r-markdown.html"><a href="reporting-in-r-markdown.html#first-r-markdown-document"><i class="fa fa-check"></i><b>5.2.1</b> First R Markdown document</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="reporting-in-r-markdown.html"><a href="reporting-in-r-markdown.html#activity-4"><i class="fa fa-check"></i><b>5.3</b> Activity</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html"><i class="fa fa-check"></i><b>6</b> Visual exploratory analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#data-visualization"><i class="fa fa-check"></i><b>6.2</b> Data visualization</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#prepare-the-rmd-document-and-data"><i class="fa fa-check"></i><b>6.2.1</b> Prepare the Rmd document and data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#categorical-variables"><i class="fa fa-check"></i><b>6.3</b> Categorical variables</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#bivariate-categorical-vs-categorical"><i class="fa fa-check"></i><b>6.3.1</b> Bivariate categorical vs categorical</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#numeric-variables"><i class="fa fa-check"></i><b>6.4</b> Numeric variables</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#univariate-numeric"><i class="fa fa-check"></i><b>6.4.1</b> Univariate numeric</a></li>
<li class="chapter" data-level="6.4.2" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#bivariate-numeric"><i class="fa fa-check"></i><b>6.4.2</b> Bivariate numeric</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#mixed-data"><i class="fa fa-check"></i><b>6.5</b> Mixed data</a></li>
<li class="chapter" data-level="6.6" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#activity-5"><i class="fa fa-check"></i><b>6.6</b> Activity</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="visual-exploratory-analysis.html"><a href="visual-exploratory-analysis.html#r-cheatsheets"><i class="fa fa-check"></i><b>6.6.1</b> R Cheatsheets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>7</b> Correlation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlation.html"><a href="correlation.html#what-is-correlation"><i class="fa fa-check"></i><b>7.1</b> What is correlation?</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="correlation.html"><a href="correlation.html#data-and-r-environment"><i class="fa fa-check"></i><b>7.1.1</b> Data and R environment</a></li>
<li class="chapter" data-level="7.1.2" data-path="correlation.html"><a href="correlation.html#visualizing-correlation"><i class="fa fa-check"></i><b>7.1.2</b> Visualizing correlation</a></li>
<li class="chapter" data-level="7.1.3" data-path="correlation.html"><a href="correlation.html#activity-1-2"><i class="fa fa-check"></i><b>7.1.3</b> Activity 1</a></li>
<li class="chapter" data-level="7.1.4" data-path="correlation.html"><a href="correlation.html#activity-2-2"><i class="fa fa-check"></i><b>7.1.4</b> Activity 2</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="correlation.html"><a href="correlation.html#measuring-correlation"><i class="fa fa-check"></i><b>7.2</b> Measuring correlation</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="correlation.html"><a href="correlation.html#activity-3-1"><i class="fa fa-check"></i><b>7.2.1</b> Activity 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="simple-lm.html"><a href="simple-lm.html"><i class="fa fa-check"></i><b>8</b> Linear model: Simple linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="simple-lm.html"><a href="simple-lm.html#welcome"><i class="fa fa-check"></i><b>8.1</b> Welcome</a></li>
<li class="chapter" data-level="8.2" data-path="simple-lm.html"><a href="simple-lm.html#introduction-to-simple-linear-regression"><i class="fa fa-check"></i><b>8.2</b> Introduction to simple linear regression</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="simple-lm.html"><a href="simple-lm.html#the-idea-behind"><i class="fa fa-check"></i><b>8.2.1</b> The idea behind</a></li>
<li class="chapter" data-level="8.2.2" data-path="simple-lm.html"><a href="simple-lm.html#formal-specification"><i class="fa fa-check"></i><b>8.2.2</b> Formal specification</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="simple-lm.html"><a href="simple-lm.html#fitting-linear-regression-in-r"><i class="fa fa-check"></i><b>8.3</b> Fitting linear regression in R</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="simple-lm.html"><a href="simple-lm.html#r-syntax"><i class="fa fa-check"></i><b>8.3.1</b> R syntax</a></li>
<li class="chapter" data-level="8.3.2" data-path="simple-lm.html"><a href="simple-lm.html#running-a-simple-linear-regression"><i class="fa fa-check"></i><b>8.3.2</b> Running a simple linear regression</a></li>
<li class="chapter" data-level="8.3.3" data-path="simple-lm.html"><a href="simple-lm.html#interpreting-results"><i class="fa fa-check"></i><b>8.3.3</b> Interpreting results</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="simple-lm.html"><a href="simple-lm.html#model-evaluation"><i class="fa fa-check"></i><b>8.4</b> Model evaluation</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="simple-lm.html"><a href="simple-lm.html#model-summary"><i class="fa fa-check"></i><b>8.4.1</b> Model summary</a></li>
<li class="chapter" data-level="8.4.2" data-path="simple-lm.html"><a href="simple-lm.html#further-checks"><i class="fa fa-check"></i><b>8.4.2</b> Further checks</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="simple-lm.html"><a href="simple-lm.html#lab-activities"><i class="fa fa-check"></i><b>8.5</b> Lab activities</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multi-lm.html"><a href="multi-lm.html"><i class="fa fa-check"></i><b>9</b> Multivariate linear model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="multi-lm.html"><a href="multi-lm.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="multi-lm.html"><a href="multi-lm.html#multivariate-model"><i class="fa fa-check"></i><b>9.2</b> Multivariate model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="multi-lm.html"><a href="multi-lm.html#paralell-slopes"><i class="fa fa-check"></i><b>9.2.1</b> Paralell slopes</a></li>
<li class="chapter" data-level="9.2.2" data-path="multi-lm.html"><a href="multi-lm.html#multivariate-model-specification"><i class="fa fa-check"></i><b>9.2.2</b> Multivariate model specification</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="multi-lm.html"><a href="multi-lm.html#r-syntax-for-the-multivariate-linear-model"><i class="fa fa-check"></i><b>9.3</b> R syntax for the multivariate linear model</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="multi-lm.html"><a href="multi-lm.html#model-evaluation-1"><i class="fa fa-check"></i><b>9.3.1</b> Model evaluation</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="multi-lm.html"><a href="multi-lm.html#assumptions"><i class="fa fa-check"></i><b>9.4</b> Assumptions</a></li>
<li class="chapter" data-level="9.5" data-path="multi-lm.html"><a href="multi-lm.html#lab-activities-1"><i class="fa fa-check"></i><b>9.5</b> Lab activities</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><i class="fa fa-check"></i><b>10</b> UG Quants summative assessment: Interpreting Quantitative Findings Report</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#introduction-3"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#create-your-research-report-template-from-github"><i class="fa fa-check"></i><b>10.2</b> Create your research report template from GitHub</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#rstudio-cloud-version"><i class="fa fa-check"></i><b>10.2.1</b> RStudio Cloud version</a></li>
<li class="chapter" data-level="10.2.2" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#rstudio-desktop-version"><i class="fa fa-check"></i><b>10.2.2</b> RStudio Desktop version</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#about-the-research-report-template"><i class="fa fa-check"></i><b>10.3</b> About the research report template</a></li>
<li class="chapter" data-level="10.4" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#activity-1-3"><i class="fa fa-check"></i><b>10.4</b> Activity 1</a></li>
<li class="chapter" data-level="10.5" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#activity-2-3"><i class="fa fa-check"></i><b>10.5</b> Activity 2</a></li>
<li class="chapter" data-level="10.6" data-path="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html"><a href="ug-quants-summative-assessment-interpreting-quantitative-findings-report.html#conclusion"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i>Workbook suggested answers</a>
<ul>
<li class="chapter" data-level="10.7" data-path="answers.html"><a href="answers.html#introduction-4"><i class="fa fa-check"></i><b>10.7</b> Introduction</a></li>
<li class="chapter" data-level="10.8" data-path="answers.html"><a href="answers.html#lab-3.-data-wrangling"><i class="fa fa-check"></i><b>10.8</b> Lab 3. Data wrangling</a></li>
<li class="chapter" data-level="10.9" data-path="answers.html"><a href="answers.html#lab-4.-exploratory-data-analysis"><i class="fa fa-check"></i><b>10.9</b> Lab 4. Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="10.9.1" data-path="answers.html"><a href="answers.html#activity-1-4"><i class="fa fa-check"></i><b>10.9.1</b> Activity #1</a></li>
<li class="chapter" data-level="10.9.2" data-path="answers.html"><a href="answers.html#activity-2-4"><i class="fa fa-check"></i><b>10.9.2</b> Activity #2</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="answers.html"><a href="answers.html#lab-6.-visual-exploratory-analysis"><i class="fa fa-check"></i><b>10.10</b> Lab 6. Visual exploratory analysis</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="answers.html"><a href="answers.html#excercices"><i class="fa fa-check"></i><b>10.10.1</b> Excercices</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="answers.html"><a href="answers.html#lab-7.-correlation"><i class="fa fa-check"></i><b>10.11</b> Lab 7. Correlation</a>
<ul>
<li class="chapter" data-level="10.11.1" data-path="answers.html"><a href="answers.html#activity-1-5"><i class="fa fa-check"></i><b>10.11.1</b> Activity 1</a></li>
</ul></li>
<li class="chapter" data-level="10.12" data-path="answers.html"><a href="answers.html#lab-8.-linear-model.-simple-linear-regression"><i class="fa fa-check"></i><b>10.12</b> Lab 8. Linear model. Simple linear regression</a>
<ul>
<li class="chapter" data-level="10.12.1" data-path="answers.html"><a href="answers.html#lab-activities-2"><i class="fa fa-check"></i><b>10.12.1</b> Lab activities</a></li>
</ul></li>
<li class="chapter" data-level="10.13" data-path="answers.html"><a href="answers.html#lab-9.-multivariate-linear-model"><i class="fa fa-check"></i><b>10.13</b> Lab 9. Multivariate linear model</a>
<ul>
<li class="chapter" data-level="10.13.1" data-path="answers.html"><a href="answers.html#lab-activities-3"><i class="fa fa-check"></i><b>10.13.1</b> Lab activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">UG Quantitative Methods in the Social Sciences lab workbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-lm" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Lab 8</span> Linear model: Simple linear regression<a href="simple-lm.html#simple-lm" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="welcome" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Welcome<a href="simple-lm.html#welcome" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous lab we learned about correlation. We visualised the relationship of different types of variables. Also, we computed one correlation measure for two numeric variables, <em>Pearson</em> correlation. This measure is useful to compute the strength and the direction of the association. However, it presents some limitations, e.g. it can only be used for numeric variables, it allows only one variable at a time, and it is appropriate to describe a linear relationship.</p>
<p>Linear regression can overcome some of these limitations and it can be extended to achieve further purposes (e.g. use multiple variables or estimate scenarios). This technique is in fact very common and one of the most popular in quantitative research in social sciences. Therefore, getting familiar with it will be important for you not only to perform your own analyses, but also to interpret and critically read literature.</p>
</div>
<div id="introduction-to-simple-linear-regression" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Introduction to simple linear regression<a href="simple-lm.html#introduction-to-simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>IMPORTANT: Linear regression is appropriate only when the dependent variable is <strong>numeric</strong> (interval/ratio).</p>
<p>However, the independent variables can be categorical, ordinal, or numeric. Also, you can include more than one independent variable to evaluate how these relate to the dependent variable. In this lab we will start using only one explanatory variable. This is know as simple linear regression.</p>
<div id="the-idea-behind" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> The idea behind<a href="simple-lm.html#the-idea-behind" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this lab, we will continue using the 2012 NILT survey to introduce linear models. To do so, please set your RStudio environment as follows:</p>
<ol style="list-style-type: decimal">
<li>Go to your ‘Quants lab group’ in <a href="https://rstudio.cloud/">RStudio Cloud</a>;</li>
<li>Create a copy of the project called ‘NILT2’ which is located in your ‘Quants lab group’ by clicking on the ‘Start’ button;</li>
<li>Once in the project, create a new ‘R Script’ file (a simple <code>R</code> script NOT an .Rmd file);</li>
<li>Save the <code>R</code> file as ‘linear_model_intro’.</li>
</ol>
<p>Reproduce the code below, by copying, pasting and running it from your new script and focus on the intuitive part of this section.</p>
<p>First, load the <code>tidyverse</code> library and read the <code>nilt_r_object.rds</code> file which is stored in the folder called ‘data’ and contains the NILT survey (<code>tidyverse</code> was installed in your session already).</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="simple-lm.html#cb74-1" aria-hidden="true"></a><span class="co">## Load the packages</span></span>
<span id="cb74-2"><a href="simple-lm.html#cb74-2" aria-hidden="true"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb74-3"><a href="simple-lm.html#cb74-3" aria-hidden="true"></a><span class="co"># Read the data from the .rds file</span></span>
<span id="cb74-4"><a href="simple-lm.html#cb74-4" aria-hidden="true"></a>nilt &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data/nilt_r_object.rds&quot;</span>)</span></code></pre></div>
<p>This dataset is exactly the same as the one you processed in previous labs.</p>
<p>We will re-revisit the example of the respondent’s spouse/partner characteristics. To keep things simple, let’s create a minimal sample of the dataset including only 40 random observations:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="simple-lm.html#cb75-1" aria-hidden="true"></a><span class="co"># select a small random sample</span></span>
<span id="cb75-2"><a href="simple-lm.html#cb75-2" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb75-3"><a href="simple-lm.html#cb75-3" aria-hidden="true"></a><span class="co"># Filter where partner&#39;s age is not NA and take a random sample of 40</span></span>
<span id="cb75-4"><a href="simple-lm.html#cb75-4" aria-hidden="true"></a>nilt_sample &lt;-<span class="st"> </span><span class="kw">filter</span>(nilt, <span class="op">!</span><span class="kw">is.na</span>(spage)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">40</span>)</span>
<span id="cb75-5"><a href="simple-lm.html#cb75-5" aria-hidden="true"></a><span class="co"># Select only respondent&#39;s age and spouse/partner&#39;s age</span></span>
<span id="cb75-6"><a href="simple-lm.html#cb75-6" aria-hidden="true"></a>nilt_sample &lt;-<span class="st"> </span><span class="kw">select</span>(nilt_sample, rage, spage)</span></code></pre></div>
<p>We will start by creating a scatter plot using the respondent’s spouse/partner age <code>spage</code> on the Y axis, and the respondent’s <code>rage</code> on the X axis.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="simple-lm.html#cb76-1" aria-hidden="true"></a><span class="co"># plot</span></span>
<span id="cb76-2"><a href="simple-lm.html#cb76-2" aria-hidden="true"></a><span class="kw">ggplot</span>(nilt_sample,  <span class="kw">aes</span>(<span class="dt">x =</span> rage, <span class="dt">y =</span> spage)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb76-3"><a href="simple-lm.html#cb76-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="st">&quot;jitter&quot;</span>) <span class="op">+</span></span>
<span id="cb76-4"><a href="simple-lm.html#cb76-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Respondent&#39;s age vs respondent’s spouse/partner age&quot;</span>, </span>
<span id="cb76-5"><a href="simple-lm.html#cb76-5" aria-hidden="true"></a>       <span class="dt">x =</span> <span class="st">&quot;Respondent&#39;s age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Respondent’s spouse/partner age&quot;</span> )</span></code></pre></div>
<p><img src="lab-workbook_files/figure-html/unnamed-chunk-85-1.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p>As you can see, even with this minimal example using 40 observations, there is a clear trend. From the plot, it seems intuitive to draw a line that describes this general trend. Imagine a friend will draw this line for you. You will have to tell them some basic references on how to do it. You can, for example, specify a start point and and end point in the plot. Alternatively, which is what we will do below, you can specify a start point and a value that describes the slope of the line. For now, our friend is <code>ggplot</code>. You have to pass these two values (start point and slope) in the <code>geom_abline()</code> function to draw a line which describes these points.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="simple-lm.html#cb77-1" aria-hidden="true"></a><span class="kw">ggplot</span>(nilt_sample, <span class="kw">aes</span>(<span class="dt">x =</span> rage, <span class="dt">y =</span> spage)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb77-2"><a href="simple-lm.html#cb77-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb77-3"><a href="simple-lm.html#cb77-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb77-4"><a href="simple-lm.html#cb77-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Respondent&#39;s age vs respondent’s spouse/partner age&quot;</span>, </span>
<span id="cb77-5"><a href="simple-lm.html#cb77-5" aria-hidden="true"></a>       <span class="dt">x =</span> <span class="st">&quot;Respondent&#39;s age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Respondent’s spouse/partner age&quot;</span> )</span></code></pre></div>
<p><img src="lab-workbook_files/figure-html/unnamed-chunk-86-1.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p>In the guess above, it is assumed that the age of the spouse/partner might be exactly the same as the respondent. To draw a line like this, we used 0 as the starting value in the <code>geom_abline()</code> function. In statistics, this is known as the <em>intercept</em> and it is often represented with a Greek letter and a zero sub-index as <span class="math inline">\(\beta_0\)</span> (beta-naught) or with <span class="math inline">\(\alpha\)</span> (alpha). The location of the intercept can be found along the vertical axis (in this case it is not visible). The second value we passed to describe the line is the <em>slope</em>, which uses the X axis as the reference. The slope value is multiplied by the value of the X axis. Therefore, a slope of 0 is completely horizontal. In this example, a slope of 1 produces a line at 45º. The slope is often represented with the Greek letter beta and a sequential numeric sub-index like this: <span class="math inline">\(\beta_1\)</span> (beta-one).</p>
<p>We will create some points in the data frame based on these two values, the start point and the steepness factor or, formally speaking, the intercept and the slope respectively. We will store the results in a column called <code>line1</code> and print the head of this data set.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="simple-lm.html#cb78-1" aria-hidden="true"></a><span class="co"># create values for the guess line 1</span></span>
<span id="cb78-2"><a href="simple-lm.html#cb78-2" aria-hidden="true"></a>nilt_sample &lt;-<span class="st"> </span>nilt_sample <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-3"><a href="simple-lm.html#cb78-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">line1 =</span> <span class="dv">0</span> <span class="op">+</span><span class="st"> </span>rage <span class="op">*</span><span class="st"> </span><span class="dv">1</span>)</span>
<span id="cb78-4"><a href="simple-lm.html#cb78-4" aria-hidden="true"></a><span class="co"># print results</span></span>
<span id="cb78-5"><a href="simple-lm.html#cb78-5" aria-hidden="true"></a><span class="kw">head</span>(nilt_sample)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##    rage spage     line1
##   &lt;dbl&gt; &lt;dbl+lbl&gt; &lt;dbl&gt;
## 1    40 39           40
## 2    54 51           54
## 3    66 59           66
## 4    60 71           60
## 5    35 34           35
## 6    67 57           67</code></pre>
<p>From the above, you can notice that the respondent’s age <code>rage</code> and the column that we just created <code>line1</code>, are identical…So, that is our guess for now. The partner’s age is the same as the respondent’s.</p>
<p>Is the line we just drew good enough to represent the general trend in the relationship above? To answer this question, we can measure the distance of each point of the plot to the line 1, as shown by the dashed segment in the plot below.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="simple-lm.html#cb80-1" aria-hidden="true"></a><span class="kw">ggplot</span>(nilt_sample, <span class="kw">aes</span>(<span class="dt">x =</span> rage, <span class="dt">y =</span> spage)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb80-2"><a href="simple-lm.html#cb80-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb80-3"><a href="simple-lm.html#cb80-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb80-4"><a href="simple-lm.html#cb80-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">xend =</span> rage, <span class="dt">yend =</span> line1), <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></span>
<span id="cb80-5"><a href="simple-lm.html#cb80-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Respondent&#39;s age vs respondent’s spouse/partner age&quot;</span>, </span>
<span id="cb80-6"><a href="simple-lm.html#cb80-6" aria-hidden="true"></a>       <span class="dt">x =</span> <span class="st">&quot;Respondent&#39;s age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Respondent’s spouse/partner age&quot;</span> )</span></code></pre></div>
<p><img src="lab-workbook_files/figure-html/unnamed-chunk-88-1.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p>This distance difference is known as the residual or the error and it is often expressed with the Greek letter <span class="math inline">\(\epsilon\)</span> (epsilon). Numerically, we can calculate this by computing the difference between the known value (the observed) and the <em>guessed</em> number. Formally, the guessed number is called the expected value (also known as predicted/estimated value). Normally, the expected values in statistics are represented by putting a hat like this <span class="math inline">\(\hat{}\)</span> on the letters. Since the independent variable is usually located on the Y axis, the expected value is differentiated from the observed values by putting the hat on the Y like this: <span class="math inline">\(\hat{y}\)</span> (y-hat).</p>
<p>Let’s estimate the residuals for each of the observations by subtracting <span class="math inline">\(\hat{y}_i\)</span> from <span class="math inline">\(y_i\)</span> (<code>spage</code> - <code>line1</code>) and store it in a column called <code>residuals</code>. Print the head of the data set after.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="simple-lm.html#cb81-1" aria-hidden="true"></a><span class="co"># estimate residuals</span></span>
<span id="cb81-2"><a href="simple-lm.html#cb81-2" aria-hidden="true"></a>nilt_sample &lt;-<span class="st"> </span>nilt_sample <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb81-3"><a href="simple-lm.html#cb81-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">residuals =</span> spage <span class="op">-</span><span class="st"> </span>line1)</span>
<span id="cb81-4"><a href="simple-lm.html#cb81-4" aria-hidden="true"></a><span class="co"># print first 6 values</span></span>
<span id="cb81-5"><a href="simple-lm.html#cb81-5" aria-hidden="true"></a><span class="kw">head</span>(nilt_sample)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##    rage spage     line1 residuals
##   &lt;dbl&gt; &lt;dbl+lbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1    40 39           40        -1
## 2    54 51           54        -3
## 3    66 59           66        -7
## 4    60 71           60        11
## 5    35 34           35        -1
## 6    67 57           67       -10</code></pre>
<p>Coming back to the question, is my line good enough? We could sum all these residuals as an overall measure to know how good my line is. From the previous plot, we see that some of the expected ages exceed the actual values and others are below. This produces negative and positive residuals. If we simply sum them, they would compensate each other and this would not tell us much about the overall magnitude of the difference. To overcome this, we can multiply the differences by themselves (to make all numbers positive) and then sum them all together. This is known as the <em>sum of squared residuals</em> (SSR) and we can use this as the criterion to measure how good my line is with respect to the overall trend of the points.</p>
<p>For line 1, we can easily calculate the SSR as follows:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="simple-lm.html#cb83-1" aria-hidden="true"></a><span class="kw">sum</span>((nilt_sample<span class="op">$</span>residuals) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1325</code></pre>
<p>The sum of squared residuals for line 1 is 1,325.</p>
<p>We can try different lines to find the combination of intercept and slope that produces the smallest error (SSR). To our luck, we can find the best values using a well established technique called <em>Ordinary Least Squares</em> (OLS). This technique finds the optimal solution by the principle of maxima and minima. We do not need to know the details for now. The important thing is that this procedure guarantees to find a line that produces the smallest possible error (SSR).</p>
<p>In <code>R</code>, it is very simple to fit a linear model and we do not need to go through each of the steps above <em>manually</em> nor to memorise all the steps. To do this, simply use the function <code>lm()</code>, save the result in an object called <code>m1</code> and print it.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="simple-lm.html#cb85-1" aria-hidden="true"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(spage <span class="op">~</span><span class="st"> </span>rage, nilt_sample)</span>
<span id="cb85-2"><a href="simple-lm.html#cb85-2" aria-hidden="true"></a>m1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = spage ~ rage, data = nilt_sample)
## 
## Coefficients:
## (Intercept)         rage  
##       6.299        0.875</code></pre>
<p>So, this is the optimal intercept <span class="math inline">\(\beta_0\)</span> and slope <span class="math inline">\(\beta_1\)</span> that produces the least sum of the square. Let’s see what the SSR is compared to my arbitrary guess above:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="simple-lm.html#cb87-1" aria-hidden="true"></a><span class="kw">sum</span>(<span class="kw">residuals</span>(m1) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1175.209</code></pre>
<p>Yes, this is better than before (because the value is smaller)!</p>
<p>Let’s plot the line we guessed and the optimal line together:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="simple-lm.html#cb89-1" aria-hidden="true"></a><span class="kw">ggplot</span>(nilt_sample, <span class="kw">aes</span>(<span class="dt">x =</span> rage, <span class="dt">y =</span> spage)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb89-2"><a href="simple-lm.html#cb89-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb89-3"><a href="simple-lm.html#cb89-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb89-4"><a href="simple-lm.html#cb89-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb89-5"><a href="simple-lm.html#cb89-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Respondent&#39;s age vs respondent’s spouse/partner age&quot;</span>, </span>
<span id="cb89-6"><a href="simple-lm.html#cb89-6" aria-hidden="true"></a>       <span class="dt">x =</span> <span class="st">&quot;Respondent&#39;s age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Respondent’s spouse/partner age&quot;</span> )</span></code></pre></div>
<p><img src="lab-workbook_files/figure-html/unnamed-chunk-93-1.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p>The blue is the optimal solution, whereas the red was just an arbitrary guess. We can see that the optimal is more balanced than the red in relation to the observed data points.</p>
</div>
<div id="formal-specification" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Formal specification<a href="simple-lm.html#formal-specification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now you are ready for the the formal specification of the linear model. After the introduction above, it is easy to take the pieces apart. In essence, the simple linear model is telling us that the dependent value <span class="math inline">\(y\)</span> is defined by a line that intersects the vertical axis at <span class="math inline">\(\beta_0\)</span>, plus the multiplication of the slope <span class="math inline">\(\beta_1\)</span> by the value of <span class="math inline">\(x_1\)</span>, plus some residual <span class="math inline">\(\epsilon\)</span>. The second part of the equation is just telling us that the residuals are normally distributed (that is when a histogram of the residuals follows a bell-shaped curve).</p>
<p><span class="math display">\[
\begin{align}
y = \beta_0 + \beta_1 * x_1 + \epsilon, &amp;&amp; \epsilon ~ N(0, \sigma)  
\end{align}
\]</span></p>
<p>You do not need to memorize this equation, but being familiar to this type of notation will help you to expand your skills in quantitative research.</p>
</div>
</div>
<div id="fitting-linear-regression-in-r" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Fitting linear regression in R<a href="simple-lm.html#fitting-linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="r-syntax" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> R syntax<a href="simple-lm.html#r-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We already fitted our first linear model using the <code>lm()</code> above, which of course stands for <em>linear model</em>, but we did not discuss the specifications needed in this function. The first argument takes the dependent variable, then, we use tilde <code>~</code> to express that this is <em>followed by</em> the independent variable. Then, we specify the data set separated by a comma, as shown below (this is just a conceptual example, it does not actually run!):</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="simple-lm.html#cb90-1" aria-hidden="true"></a><span class="kw">lm</span>(dependent_variable <span class="op">~</span><span class="st"> </span>independent_variable, data)</span></code></pre></div>
</div>
<div id="running-a-simple-linear-regression" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Running a simple linear regression<a href="simple-lm.html#running-a-simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, let’s try with the full data set. First, we will fit a linear model using the same variables as the example above but including all the observations (remember that before we were working only with a small random sample). The first argument is the respondent’s spouse/partner age <code>spage</code>, followed by the respondent’s age <code>rage</code>. Let’s assign the model to an object called <code>m2</code> and print it after.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="simple-lm.html#cb91-1" aria-hidden="true"></a>m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(spage <span class="op">~</span><span class="st"> </span>rage, nilt)</span>
<span id="cb91-2"><a href="simple-lm.html#cb91-2" aria-hidden="true"></a>m2</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = spage ~ rage, data = nilt)
## 
## Coefficients:
## (Intercept)         rage  
##      3.7039       0.9287</code></pre>
<p>The output first displays the formula employed to estimate the model. Then, it show us the estimated values for the intercept and the slope for the age of the respondent, these estimated values are called coefficients. In this model, the coefficients differ from the ones in the example above (m1). This is because we now have more information to fit this line. Despite the difference, we see that the relationship is still in the same direction (positive). In fact, the value of the slope <span class="math inline">\(\beta_1\)</span> did not change much if you look at it carefully (0.87 vs 0.92).</p>
</div>
<div id="interpreting-results" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Interpreting results<a href="simple-lm.html#interpreting-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>But what are the slope and intercept telling us? The first thing to note is that the slope is positive, which means that the relationship between the respondent age and their partner are in the same direction. When the age of the respondent goes up, the age of their partner is expected to go up as well.</p>
<p>In our model, the intercept does not have a meaningful interpretation on its own, it would not be logical to say that when the respondent’s age is 0 their partner would be expected to be 3.70 years old. Interpretations should be made only within the range of the values used to fit the model (the youngest age in this data set is 18). The slope can be interpreted as following: For every year older the respondent is, the partner’s age is expected to change by 0.92. In other words, the respondents are expected to have a partner who is 0.92 times years older than themselves. This means that their partners are expected to be slightly younger.</p>
<p>In this case, the units of the dependent variable are the same as the independent (age vs age) which make it easy to interpret. In reality, there might be more factors that potentially affect how people select their partners (e.g. genders, education, race/ethnicity, etc.). For now, we are keeping things simple using only these two variables.</p>
<p>Let’s practice with another example. What if we are interested in income? We can use personal income <code>persinc2</code> as the dependent variable and the number of hours worked a week <code>rhourswk</code> as the independent variable. We’ll assign the result to an object called <code>m3</code>.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="simple-lm.html#cb93-1" aria-hidden="true"></a>m3 &lt;-<span class="st"> </span><span class="kw">lm</span>(persinc2 <span class="op">~</span><span class="st"> </span>rhourswk, <span class="dt">data =</span> nilt)</span>
<span id="cb93-2"><a href="simple-lm.html#cb93-2" aria-hidden="true"></a>m3</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = persinc2 ~ rhourswk, data = nilt)
## 
## Coefficients:
## (Intercept)     rhourswk  
##      5170.4        463.2</code></pre>
<p>This time, the coefficients look quite different. The results are telling us that for every additional hour worked a week a respondent is expected to earn £463.2 more a year than other respondent. Note that the input units are not the same in the interpretation. The dependent variable is in pounds earned a year and the independent is in hours worked a week. Does this mean that someone who works 0 hours a week is expected to earn £5170.4 a year (given the fitted model <span class="math inline">\(\hat{persinc2} = 5170.4 + 0*463.2\)</span>) or that someone who works 110 hours a week (impossible!) is expected to earn £56K a year? We should only make reasonable interpretations of the coefficients within the range analysed.</p>
<p>Finally, an important thing to know when interpreting linear models using cross sectional data (data collected in a single time point only) is: <strong><em>correlation does not imply causation</em></strong>. Variables are often correlated with other non-observed variables which may cause the effects observed on the independent variable in reality. This is why we cannot always be sure that X is causing the observed changes on Y.</p>
</div>
</div>
<div id="model-evaluation" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Model evaluation<a href="simple-lm.html#model-evaluation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the next section, we suggest you to focus on the interpretation of the results of the linear model. You do not need to reproduce the code.</p>
<div id="model-summary" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Model summary<a href="simple-lm.html#model-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So far, we have talked about the basics of the linear model. If we print a summary of the model, we can obtain more information to evaluate it.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="simple-lm.html#cb95-1" aria-hidden="true"></a><span class="kw">summary</span>(m2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = spage ~ rage, data = nilt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.211  -2.494   0.075   2.505  17.578 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.70389    0.66566   5.564    4e-08 ***
## rage         0.92869    0.01283  72.386   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.898 on 589 degrees of freedom
##   (613 observations deleted due to missingness)
## Multiple R-squared:  0.8989, Adjusted R-squared:  0.8988 
## F-statistic:  5240 on 1 and 589 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>There are a lot of numbers from the result. Let’s break down the information into different pieces: first the call, second the residuals, third the coefficients, and fourth the goodness-of-fit measures, as shown below:</p>
<div class="figure">
<img src="images/r_studio_lab6_model_summary.png" alt="" />
<p class="caption">Model summary</p>
</div>
<p>The first part, <strong>Call</strong>, is simply printing the variables that were used to produce the models.</p>
<p>The second part, the <strong>Residuals</strong>, provides a small summary of the residuals by quartile, including minimum and maximum residual values. Remember the second part of the formal specification of the model? Well, this is where we can see in practice the distribution of the residuals. If we look at the first and third quartile, we can see that that 50% of the predicted values by the model are <span class="math inline">\(\pm\)</span> 2.5 years old away form the observed partner’s age…not that bad.</p>
<p>The third part is about the <strong>coefficients</strong>. This time, the summary provides more information about the intercept and the slope than just the estimated coefficients as before. Usually, we focus on the independent variables in this section, <code>rage</code> in our case. The second column, standard error, tell us how large the error of the slope is, which is small for our variable. The third and fourth columns provide measures about the statistical significance of the relationship between the dependent and independent variable. The most commonly reported is the p-value (the fourth column). When these values contains many digits, R reports the result in scientific notation. In our result the p-value is <code>&lt;2e-16</code> (the real equivalent number is &lt;0.0000000000000002, if you want to know more about scientific notation click <a href="https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php#:~:text=The%20proper%20format%20for%20scientific,equivalent%20to%20the%20original%20number.">here</a>). As a general agreed principle, <strong>if the p-value is equal or less than 0.05 (<span class="math inline">\(p\)</span> ≤ 0.05), we can reject the null hypothesis, and say that the relationship between the dependent variable and the independent is significant.</strong> In our case, the p-value is far lower than 0.05. So, we can say that the relationship between the respondent’s spouse/partner age and the respondent’s age is significant. In fact, R includes codes for each coefficient to help us to identify the significance. In our result, we got three stars/asterisks. This is because the value is less than 0.001. R assigns two stars if the p-value is less than 0.01, and one star if it is lower than 0.05.</p>
<p>In the fourth area, we have various goodness-of-fit measures. Overall, these measures tell us how well the model represents our data. For now, let’s focus on the <em>adjusted r-squared</em> and the sample size. The r-squared is a value that goes from 0 to 1. 0 means that model is not explaining any of the variance, whereas 1 would mean a perfect model. In social sciences we do not see high values often. The adjusted r-squared can be understood as the percentage variance that the model is able to explain. In the example above, the model explains 89.88% percent of the total variance. This is a good fit, but this is because we are modelling a quite “obvious” relationship. The r-squared does not represent how good or bad our work is. You may wonder why we do not report the sum of squared residuals (SSR), as we just learned. This is because the scale of the SSR is in the units used to fit the model, which would make it difficult to compare our model with other models that use different units or different variables. Conversely, the adjusted r-squared is expressed in relative terms which makes it a more suitable measure to compare with other models. An important thing to note is that the output is telling us that this model excluded 613 observations which were missing in our dataset. This is because we do not have the age of the respondent’s partner in 613 of the rows. This missingness may be because the respondent do not have a partner, refused to provide the information, etc.</p>
<p>In academic papers in the social sciences, usually the measures reported are the coefficients, p-values, the adjusted r-squared, and the size of the sample used to fit the model (number of observations).</p>
</div>
<div id="further-checks" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Further checks<a href="simple-lm.html#further-checks" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The linear model, as many other techniques in statistics, relies on assumptions. These refer to characteristics of the data that are taken for granted to generate the estimates. It is the task of the modeller/analyst to make sure the data used follows these assumptions. One simple yet important check is to examine the distribution of the residuals, which ought to follow a normal distribution.</p>
<p>Does the residuals follow a normal distribution in <code>m1</code>? We can go further and plot a histogram to graphically evaluate it. Use the function <code>residuals()</code> to extract the residuals from our object <code>m2</code>, and then plot a histogram with the r-base function <code>hist()</code>.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="simple-lm.html#cb97-1" aria-hidden="true"></a><span class="kw">hist</span>(<span class="kw">residuals</span>(m2), <span class="dt">breaks =</span> <span class="dv">20</span>)</span></code></pre></div>
<p><img src="lab-workbook_files/figure-html/unnamed-chunk-98-1.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p>Overall, it seems that the residuals follow the normal distribution reasonably well, with the exception of the negative value to the left of the plot. Very often when there is a strange distribution or different to the normal is because one of the assumptions is violated. If that is the case we cannot trust the coefficient estimates. In the next lab we will talk more about the assumptions of the linear model. For now, we will leave it here and get some practice.</p>
</div>
</div>
<div id="lab-activities" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Lab activities<a href="simple-lm.html#lab-activities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the <code>linear_model_intro.R</code> script, use the <code>nilt</code> dataset in to:</p>
<ol style="list-style-type: decimal">
<li>Plot a scatter plot using <code>ggplot</code>. In the aesthetics, locate <code>rhourswk</code> in the X axis, and <code>persinc2</code> in the Y axis. In the <code>geom_point()</code> jitter the points by specifying the <code>position = 'jitter'</code>. Also, include the best fit line using the <code>geom_smooth()</code> function, and specify the <code>method = 'lm'</code> inside.</li>
<li>Print the summary of <code>m3</code> using the <code>summary()</code> function.</li>
<li>Is the the relationship of hours worked a week significant?</li>
<li>What is the adjusted r-squared? How would you interpret it?</li>
<li>What is the sample size to fit the model?</li>
<li>What is the expected income in pounds a year for a respondent who works 30 hours a week according to coefficients of this model?</li>
<li>Plot a histogram of the residuals of <code>m3</code> using the <code>residuals()</code> function inside <code>hist()</code>. Do the residuals look normally distributed (as in a bell-shaped curve)?</li>
<li>Discuss your answers with your neighbour or tutor.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multi-lm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["lab-workbook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
